Repository bitcoin-sv/spv-wallet, pull requests merged in 2022-07, with the labels that each got.

#91 Added new utxo endpoints, including the original transaction
  actions/utxos/count.go
  actions/utxos/get.go
  actions/utxos/routes.go
  go.sum
  graph/generated/generated.go
  graph/schema.graphqls
  graph/schema.resolvers.go
Labels: feature, update

#104 Upgrade bux (replace datastore with go-datastore)
  Makefile
  actions/methods.go
  config/config.go
  config/config_test.go
  config/datastore.go
  config/datastore_test.go
  config/services.go
  go.mod
  go.sum
  gqlgen.yml
  graph/admin.resolvers.go
  graph/generated/generated.go
  graph/schema.resolvers.go
Labels: refactor, feature, update

#108 docker-compose missing healtchecks
  docker-compose.yml
Labels: update
