Repository bitcoin-sv/spv-wallet, pull requests merged in 2022-04, with the labels that each got.

#42 Fixed paymail action according to new bux method signature
  actions/paymail/create.go
Labels: update

#43 Added missing admin graphql endpoints for paymail
  gqlgen.yml
  graph/admin.graphqls
  graph/admin.resolvers.go
  graph/generated/generated.go
  graph/schema.graphqls
Labels: update

#44 Fixed init of model options in graphql resolver
  graph/schema.resolvers.go
Labels: update

#52 Added notifications config
  config/config.go
  config/services.go
Labels: feature, update

#49 Added api router compatible logging to graphql
  actions/graphql/routes.go
  config/graphql.go
  go.mod
  go.sum
Labels: feature, update

#39 Monitor in Chainstate
  config/config.go
  config/envs/development.json
  config/envs/test.json
  config/services.go
  go.mod
  go.sum
Labels: work-in-progress, update
