Repository bitcoin-sv/spv-wallet, pull requests merged in 2023-12, with the labels that each got.

#364 chore(BUX-XXX): update bux to v0.7.0
  go.mod
  go.sum
Labels: chore, update

#365 feat(BUX-200): unify logs
  .golangci.yml
  README.md
  actions/graphql/routes.go
  actions/paymail/routes.go
  cmd/server/main.go
  config/config.go
  config/envs/development.json
  config/envs/docker-compose.json
  config/envs/production.json
  config/envs/staging.json
  config/envs/test.json
  config/load.go
  config/services.go
  go.mod
  go.sum
  logging/logging.go
  server/server.go
Labels: feature

#374 feat(BUX-361): env update in script that runs bux-server
  start-bux-server.sh
Labels: work-in-progress

#377 feat(BUX-421): replace router logger
  actions/middleware.go
Labels: feature

#380 chore(BUX-416) disable monitor
  config.example.yaml
  config/config.go
  config/defaults.go
  config/services.go
  go.mod
  go.sum
Labels: update

#386 chore(BUX-426): BroadcastClientAPIs as struct
  config/config.go
  config/defaults.go
  config/services.go
Labels: update
