Repository bitcoin-sv/spv-wallet, pull requests merged in 2023-06, with the labels that each got.

#241 fix: regeneration of graphql docs for a new version of github.com/99designs/gqlgen
  graph/admin.resolvers.go
  graph/generated/generated.go
  graph/schema.resolvers.go
Labels: bug-P3

#249 feat: cgo-enabled flag
  Dockerfile
Labels: feature, hot-fix

#254 feat: usage of mapi fee quotes
  config/config.go
  config/envs/development.json
  config/envs/docker-compose.json
  config/envs/production.json
  config/envs/staging.json
  config/envs/test.json
  config/services.go
Labels: feature
