Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-10, with the labels that each got.

#716 chore(SPV-1054) remove synctx model and unused constants
  engine/client_options_test.go
  engine/definitions.go
  engine/model_sync_results.go
  engine/model_sync_status.go
  engine/model_sync_transactions.go
  engine/model_transactions.go
  engine/models_test.go
  engine/spverrors/definitions.go
  mappings/transaction.go
  mappings/transactions_old.go
Labels: tested, regression-tests

#715 feat(SPV-1074): new chain query
  .golangci-lint.yml
  actions/transactions/broadcast_callback.go
  config/services.go
  engine/action_transaction.go
  engine/chain/chain_service.go
  engine/chain/interface.go
  engine/chain/internal/query/arc_mock_test.go
  engine/chain/internal/query/query_service.go
  engine/chain/internal/query/query_service_test.go
  engine/chain/models/arc_error.go
  engine/chain/models/tx_info.go
  engine/chain/models/txstatus.go
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/interface.go
  engine/model_transactions.go
  engine/paymail.go
  engine/record_tx_strategy_outgoing_tx.go
  engine/spverrors/definitions.go
  engine/tx_sync_task.go
Labels: tested, regression-tests

#718 fix(SPV-000): decrease cache TTL for capabilities
  engine/paymail/paymail_service_client.go
Labels: tested, regression-tests

#720 Feat/SPV-808/mongodb cleanup remove bson from metadata files
  engine/datastore/customtypes/nullstring.go
  engine/datastore/customtypes/nullstring_test.go
  engine/datastore/customtypes/nulltime.go
  engine/datastore/customtypes/nulltime_test.go
  engine/datastore/definitions.go
  engine/datastore/models.go
  engine/datastore/utils.go
  engine/datastore/utils_test.go
  engine/datastore/where_mocks_test.go
  engine/examples/client/custom_models/custom_models.go
  engine/model_access_keys.go
  engine/model_contact.go
  engine/model_destinations.go
  engine/model_draft_transactions.go
  engine/model_metadata.go
  engine/model_metadata_test.go
  engine/model_paymail_addresses.go
  engine/model_transaction_config.go
  engine/model_transactions.go
  engine/model_utxos.go
  engine/model_webhook.go
  engine/model_xpubs.go
  engine/models.go
  engine/models_test.go
  go.mod
  go.sum
Labels: tested, regression-tests

#719 feat(spv-1062) removing new relic
  cmd/main.go
  config.example.yaml
  config/config.go
  config/config_test.go
  config/defaults.go
  config/services.go
  config/services_test.go
  config/validate.go
  config/validate_authentication_test.go
  config/validate_new_relic.go
  config/validate_new_relic_test.go
  config/validate_nodes_test.go
  engine/action_access_key.go
  engine/action_destination.go
  engine/action_draft_transaction.go
  engine/action_paymails.go
  engine/action_transaction.go
  engine/action_utxo.go
  engine/action_xpub.go
  engine/admin_actions_stats.go
  engine/chainstate/broadcast_client_init.go
  engine/chainstate/client.go
  engine/chainstate/client_options.go
  engine/chainstate/client_options_test.go
  engine/chainstate/interface.go
  engine/client.go
  engine/client_options.go
  engine/client_options_test.go
  engine/client_test.go
  engine/cluster/client.go
  engine/cluster/client_options.go
  engine/datastore/client.go
  engine/datastore/client_options.go
  engine/datastore/client_options_test.go
  engine/datastore/interface.go
  engine/datastore/migrate.go
  engine/datastore/sql.go
  engine/examples/client/new_relic/new_relic.go
  engine/interface.go
  engine/spv_wallet_engine_suite_mocks_test.go
  engine/spv_wallet_engine_suite_test.go
  engine/spv_wallet_engine_test.go
  engine/taskmanager/interface.go
  engine/taskmanager/options.go
  engine/taskmanager/options_test.go
  engine/taskmanager/taskmanager.go
  engine/taskmanager/taskq_test.go
  engine/tester/cache.go
  engine/tester/cache_test.go
  engine/tester/new_relic.go
  engine/tester/new_relic_test.go
  go.mod
  server/server.go
Labels: feature, tested, regression-tests

#722 refactor(SPV-1071): cleanup in config package.
  cmd/main.go
  config.example.yaml
  config/check_block_header_service.go
  config/config.go
  config/config_test.go
  config/config_to_options.go
  config/defaults.go
  config/flags.go
  config/load_config.go
  config/load_config_test.go
  config/services.go
  config/services_test.go
  config/task_manager.go
  config/validate.go
  config/validate_app_config.go
  config/validate_app_config_test.go
  config/validate_arc.go
  config/validate_arc_test.go
  config/validate_authentication_test.go
  config/validate_bhs_test.go
  config/validate_cachestore_test.go
  config/validate_datastore_test.go
  config/validate_nodes.go
  config/validate_nodes_test.go
  config/validate_paymail_test.go
  config/validate_server_test.go
  engine/client.go
  engine/logging/adapters.go
  engine/tester/logger.go
  logging/gin_loggers.go
  logging/logging.go
  server/middleware/appcontext_middleware.go
  server/server.go
  server/server_test.go
  tests/tests.go
Labels: tested, regression-tests

#727 chore(deps): Chore deps updates
  .github/workflows/run-tests.yml
  Dockerfile
  go.mod
  go.sum
Labels: tested, regression-tests

#728 feat(SPV-1075): Introduced Junglebus client to get transaction
  engine/chain/errors/junglebus_errors.go
  engine/chain/internal/junglebus/fetch_transaction.go
  engine/chain/internal/junglebus/fetch_transaction_test.go
  engine/chain/internal/junglebus/junglebus_mock_test.go
  engine/chain/internal/junglebus/service.go
  engine/chain/internal/junglebus/transaction_response.go
Labels: tested

#729 feat(SPV-1061) new EF converter
  engine/chain/internal/ef/converter.go
  engine/chain/internal/ef/converter_test.go
  engine/chain/internal/ef/errors.go
  engine/chain/internal/ef/mock_txgetter_test.go
  engine/chain/internal/ef/unsourced_inputs.go
Labels: tested

#730 test(SPV-1086): get shared config endpoint tests
  actions/sharedconfig/get_endpoint_test.go
  actions/testabilities/ability_spvwallet_application.go
  actions/testabilities/assert_spvwallet_application.go
  actions/testabilities/fixture_spvwallet_application.go
  actions/testabilities/test_server.go
  engine/paymailaddress/testabilities/ability_paymail_address_service.go
  engine/tester/fixtures/paymail.go
  engine/tester/fixtures/users_fixtures.go
  engine/transaction/draft/create_draft_test.go
  engine/transaction/draft/create_op_return_draft_test.go
  engine/transaction/draft/create_paymail_draft_test.go
  mappings/draft/to_engine_test.go
Labels: tested

#732 test(SPV-1086): mock external dependencies in endpoint tests
  actions/testabilities/fixture_spvwallet_application.go
  config/config_to_options.go
  engine/chain/chain_service.go
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/client_options_test.go
  engine/definitions.go
  engine/interface.go
Labels: tested, regression-tests

#723 feat(SPV-1085) merkle roots verifier
  cmd/main.go
  config/check_block_header_service.go
  config/config.go
  config/config_to_options.go
  engine/chain/chain_service.go
  engine/chain/errors/bhs_errors.go
  engine/chain/interface.go
  engine/chain/internal/arc/policy_test.go
  engine/chain/internal/arc/query_transaction_test.go
  engine/chain/internal/bhs/bhs_mock_test.go
  engine/chain/internal/bhs/healthcheck.go
  engine/chain/internal/bhs/healthcheck_test.go
  engine/chain/internal/bhs/service.go
  engine/chain/internal/bhs/verify_mr.go
  engine/chain/internal/bhs/verify_mr_test.go
  engine/chain/models/bhs_config.go
  engine/chain/models/mr_confirmation.go
  engine/chainstate/client.go
  engine/chainstate/client_options.go
  engine/chainstate/interface.go
  engine/chainstate/merkle_root.go
  engine/chainstate/merkle_root_provider.go
  engine/chainstate/merkle_root_test.go
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/interface.go
  engine/paymail_service_provider.go
  engine/spverrors/definitions.go
Labels: tested, regression-tests

#740 chore(XXX): update config example with experimental features
  config.example.yaml
Labels: tested, regression-tests

#736 refactor(SPV-1079): move merkleroots to spv-wallet service
  actions/merkleroots/bhs_error_response.go
  actions/merkleroots/errors.go
  actions/merkleroots/get.go
  actions/merkleroots/get_merkleroots_from_bhs.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/chain/errors/bhs_errors.go
  engine/chain/interface.go
  engine/chain/internal/bhs/bhs_error.go
  engine/chain/internal/bhs/bhs_error_response.go
  engine/chain/internal/bhs/bhs_mock_test.go
  engine/chain/internal/bhs/get_merkleroots.go
  engine/chain/internal/bhs/get_merkleroots_test.go
  engine/chain/internal/bhs/verify_mr.go
  models/merkleroot.go
  models/page.go
Labels: refactor, tested, regression-tests

#733 fix(SPV-000): update block headers service in start.sh
  start.sh
Labels: tested

#739 refactor(SPV-1057): rename draft to transaction outlines in new tx flow.
  actions/transactions/internal/mapping/outline/outline_request_to_engine.go
  actions/transactions/internal/mapping/outline/outline_to_response.go
  actions/transactions/outlines.go
  actions/transactions/outlines_endpoint_test.go
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/client_transaction.go
  engine/interface.go
  engine/transaction/draft/create_draft_test.go
  engine/transaction/draft/testabilities/ability_draft_transaction.go
  engine/transaction/draft/testabilities/assert_draft_transaction.go
  engine/transaction/draft/testabilities/fixture_draft_transaction.go
  engine/transaction/errors/errors.go
  engine/transaction/outlines/create_draft_test.go
  engine/transaction/outlines/create_op_return_draft_test.go
  engine/transaction/outlines/create_paymail_draft_test.go
  engine/transaction/outlines/inteface.go
  engine/transaction/outlines/internal/evaluation/context.go
  engine/transaction/outlines/internal/evaluation/interface.go
  engine/transaction/outlines/outputs/op_return.go
  engine/transaction/outlines/outputs/paymail.go
  engine/transaction/outlines/outputs/spec.go
  engine/transaction/outlines/testabilities/ability_draft_transaction.go
  engine/transaction/outlines/testabilities/assert_draft_transaction.go
  engine/transaction/outlines/testabilities/fixture_draft_transaction.go
  engine/transaction/outlines/transaction.go
  engine/transaction/outlines/transaction_outlines_service.go
  engine/transaction/outlines/transaction_spec.go
  models/request/transaction_specification.go
  models/request/transaction_specification_json.go
  models/request/transaction_specification_test.go
Labels: tested

#747 ci(SPV-1114): setup builds to publish images also on AWS ECR public repo.
  .github/workflows/manual-build-dockers.yml
  .github/workflows/release.yml
  .github/workflows/trigger-regression-tests.yml
Labels: tested, regression-tests

#748 fix(XXX): fix exclusive page response json data structure
  models/page.go
Labels: tested

#745 test(SPV-1079): add endpoint tests for get merkleroots
  actions/merkleroots/get_merkleroots_endpoint_test.go
  actions/merkleroots/merkleroots_test.go
  actions/merkleroots/routes.go
  actions/merkleroots/routes_test.go
  actions/register.go
  actions/testabilities/assert_spvwallet_application.go
  actions/testabilities/fixture_block_header_service.go
  actions/testabilities/fixture_spvwallet_application.go
  engine/chain/internal/bhs/bhs_mock_test.go
  engine/chain/internal/bhs/get_merkleroots_test.go
Labels: tested

#746 SPV-1108(feat) Bump-golangci-lint-version-in-spv-wallet
  .github/workflows/release.yml
  .github/workflows/run-tests.yml
  .golangci-lint.yml
  config/config_to_options.go
  conv/convert_primitives.go
  engine/action_transaction.go
  engine/beef_tx_bytes.go
  engine/chain/internal/arc/broadcast_test.go
  engine/chain/internal/combined_txs_getter.go
  engine/chain/internal/combined_txs_getter_test.go
  engine/chain/internal/ef/mock_txgetter_test.go
  engine/chain/internal/ef/unsourced_inputs.go
  engine/chain/internal/junglebus/txs_getter.go
  engine/chain/models/arc_config.go
  engine/datastore/models.go
  engine/model_draft_transactions.go
  engine/model_paymail_addresses.go
  engine/model_xpubs.go
  engine/paymail_service_provider.go
  engine/pike_service_provider.go
  engine/script/template/p2pkh_test.go
  engine/sdk_tx_getter.go
  engine/spverrors/definitions.go
  engine/tx_service.go
  engine/tx_sync_task.go
  engine/types/type42/linking_key_test.go
  engine/utils/ripemd160.go
  engine/utils/utils.go
  mappings/fee_unit.go
  mappings/fee_unit_old.go
  models/fee_unit.go
  models/response/fee_unit.go
  regression_tests/utils.go
Labels: feature, tested, regression-tests

#755 chore(SPV-000): bump go-sdk to v1.1.10
  engine/model_access_keys.go
  engine/model_access_keys_test.go
  engine/model_draft_transactions_test.go
  engine/model_paymail_addresses.go
  engine/model_paymail_addresses_test.go
  engine/script/template/evaluate.go
  engine/script/template/p2pkh_test.go
  engine/types/type42/linking_key.go
  engine/types/type42/linking_key_test.go
  engine/utils/utils_test.go
  go.mod
  go.sum
Labels: tested, regression-tests

#752 refactor(SPV-1058): provide method for setting up engine without server.
  actions/merkleroots/get_merkleroots_endpoint_test.go
  actions/testabilities/fixture_block_header_service.go
  actions/testabilities/fixture_spvwallet_application.go
  config/config_to_options.go
  engine/testabilities/fixture_block_header_service.go
  engine/testabilities/fixture_engine.go
  engine/tester/fixtures/bhs_fixtures.go
Labels: tested

#757 Feat/spv 1119/add a search option by xpubid for admin only
  actions/admin/helpers.go
  actions/admin/models.go
  actions/admin/transactions.go
  engine/spverrors/definitions.go
  models/filter/transaction_admin_filter.go
Labels: tested
