Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-08, with the labels that each got.

#633 feat(SPV-835): add /configs/shared router group
  actions/sharedconfig/get.go
  actions/sharedconfig/routes.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  models/response/shared_config.go
  server/server.go
Labels: tested

#656 deps(SPV-970): update dependencies
  go.mod
  go.sum
Labels: dependencies, tested

#657 feat(SPV-980): return empty access keys slice when no records found
  engine/action_access_key.go
Labels: tested

#658 fix(SPV-835): OldModel name breaks backward compatibility of the model package.
  mappings/access_keys.go
  mappings/common/common.go
  mappings/contact.go
  mappings/destination.go
  mappings/paymail_address.go
  mappings/transaction.go
  mappings/utxo.go
  mappings/xpub.go
  models/access_key.go
  models/block_header.go
  models/common/model.go
  models/contact.go
  models/destination.go
  models/draft_transaction.go
  models/models_test.go
  models/paymail_address.go
  models/response/common_model.go
  models/response/xpub.go
  models/sync_transaction.go
  models/transaction.go
  models/utxo.go
  models/xpub.go
Labels: tested

#635 feat(SPV-837): add /users/current/keys router group
  actions/access_keys/access_keys_test.go
  actions/access_keys/create.go
  actions/access_keys/get.go
  actions/access_keys/revoke.go
  actions/access_keys/routes.go
  actions/access_keys/search.go
  actions/admin/access_keys.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  mappings/access_keys.go
  models/response/access_key.go
  server/server.go
Labels: tested

#661 ci(SPV-992): use dependabot update groups
  .github/dependabot.yml
Labels: tested

#666 fix(SPV-000): linter errors regarding string formating.
  config/services.go
  config/validate_nodes.go
  config/validate_paymail.go
  engine/chainstate/transaction.go
  engine/logging/adapters.go
  engine/taskmanager/taskq.go
Labels: chore, tested

#665 feat(SPV-793): create functions to help parsing metadata from query string.
  internal/query/gin_map.go
  internal/query/gin_map_test.go
  internal/query/map.go
Labels: tested

#672 fix(SPV-000): change lint version
  .github/workflows/run-tests.yml
Labels: tested

#673 feat(SPV-793): function which to make map from query params or returns errors
  internal/query/gin_map.go
  internal/query/gin_map_test.go
  internal/query/map.go
Labels: tested

#675 feat(SPV-793): add function to parse query params into new search struct
  engine/spverrors/definitions.go
  internal/query/parse.go
  internal/query/parse_test.go
  mappings/filter_old.go
  mappings/search.go
  models/filter/access_key_filter.go
  models/filter/contact_filter.go
  models/filter/destination_filter.go
  models/filter/paymail_filter.go
  models/filter/search_params.go
  models/filter/transaction_filter.go
  models/filter/utxo_filter.go
  models/filter/xpub_filter.go
Labels: tested

#671 feat(SPV-930): get all webhooks - admin endpoint
  actions/admin/routes.go
  actions/admin/webhooks.go
  engine/client_internal.go
  engine/interface.go
  engine/notifications/webhook_manager.go
  engine/spverrors/definitions.go
  mappings/webhook.go
  models/webhook.go
Labels: feature, tested

#669 feat(SPV-891): adds workflow for regression tests
  .github/labels.yml
  .github/workflows/trigger-regression-tests.yml
Labels: test, tested

#674 fix(SPV-1013): swaps errors to those in spverrors, bumps versions of imports
  regression_tests/go.mod
  regression_tests/go.sum
  regression_tests/operator.go
  regression_tests/utils.go
Labels: tested

#678 feat(SPV-793): prepare common way for generating swagger for search endpoints
  actions/access_keys/search.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  models/swagger/access_key_params.go
  models/swagger/search_params.go
Labels: tested

#659 feat(SPV-928): access keys search endpoint
  actions/access_keys/count.go
  actions/access_keys/create.go
  actions/access_keys/get.go
  actions/access_keys/revoke.go
  actions/access_keys/routes.go
  actions/access_keys/routes_test.go
  actions/access_keys/search.go
  actions/common/search_methods.go
  actions/contacts/routes_test.go
  actions/sharedconfig/get.go
  actions/users/get.go
  actions/users/update.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  models/filter/search_models.go
  models/swagger/access_key_params.go
Labels: refactor, tested
