Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-05, with the labels that each got.

#552 feat(BUX-754): PATCH endpoint for unconfirmed contact
  actions/contacts/routes.go
  actions/contacts/routes_test.go
  actions/contacts/unconfirm.go
  engine/action_contact.go
  engine/action_contact_test.go
  engine/interface.go
  engine/model_contact.go
Labels: tested

#554 fix(spv-642): do not rebroadcast declined transactions again
  engine/chainstate/broadcast.go
  engine/chainstate/broadcast_providers.go
  engine/chainstate/broadcast_test.go
  engine/chainstate/broadcast_utils.go
  engine/chainstate/chainstate.go
  engine/chainstate/interface.go
  engine/chainstate/minercraft_init.go
  engine/chainstate/transaction.go
  engine/go.mod
  engine/go.sum
  engine/model_sync_results.go
  engine/model_sync_transactions.go
  engine/spv_wallet_engine_test.go
  engine/sync_tx_service.go
  engine/sync_tx_service_test.go
  go.mod
  go.sum
Labels: tested

#581 feat(SPV-750): add admin contact endpoints
  actions/admin/contact.go
  actions/admin/models.go
  actions/common/search_methods.go
  actions/contacts/search.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_contact.go
  engine/interface.go
  engine/model_contact.go
  models/page.go
  server/auth/middleware.go
Labels: feature, tested

#598 feat(SPV-809): mysql & mongo removal
  README.md
  config.example.yaml
  config/config.go
  config/config_test.go
  config/defaults.go
  config/services.go
  config/validate_datastore.go
  config/validate_datastore_test.go
  docker-compose.yml
  engine/README.md
  engine/client.go
  engine/client_datastore.go
  engine/client_internal.go
  engine/client_options.go
  engine/datastore/client.go
  engine/datastore/client_options.go
  engine/datastore/client_options_test.go
  engine/datastore/client_test.go
  engine/datastore/datastore_test.go
  engine/datastore/definitions.go
  engine/datastore/engine.go
  engine/datastore/engine_test.go
  engine/datastore/index.go
  engine/datastore/interface.go
  engine/datastore/migrate.go
  engine/datastore/models.go
  engine/datastore/mongodb.go
  engine/datastore/mongodb_test.go
  engine/datastore/sql.go
  engine/datastore/sql_test.go
  engine/datastore/transaction.go
  engine/datastore/where_builder.go
  engine/datastore/where_mocks_test.go
  engine/datastore/where_test.go
  engine/db_model_transactions.go
  engine/definitions.go
  engine/examples/client/mysql/mysql.go
  engine/go.mod
  engine/go.sum
  engine/model_contact.go
  engine/model_destinations_test.go
  engine/model_paymail_addresses.go
  engine/model_utxos.go
  engine/model_xpubs_test.go
  engine/spv_wallet_engine_suite_test.go
  engine/tester/database.go
  engine/tester/embedded_test.go
  go.mod
  go.sum
  start.sh
Labels: feature, tested

#599 feat(SPV-XXX): update dependencies + make update for inner packages
  .make/go.mk
  engine/go.mod
  engine/go.sum
  go.mod
  go.sum
Labels: dependencies, tested

#595 feat(spv-790) Create outputs template and store evaluated template in destination
  engine/examples/client/pike/main.go
  engine/pike/example_test.go
  engine/pike/pike.go
  engine/pike/pike_test.go
  engine/script/template/evaluate.go
  engine/script/template/p2pkh.go
  engine/script/template/p2pkh_test.go
  engine/types/type42/linking_key.go
  engine/types/type42/linking_key_test.go
  engine/types/type42/test_helpers.go
Labels: tested

#597 SPV-807: adjust shared config
  actions/admin/routes.go
  actions/sharedconfig/get.go
  actions/sharedconfig/routes.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  server/server.go
Labels: tested
