Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-06, with the labels that each got.

#603 feat(SPV-737) unify search object & filters and move to models package
  actions/access_keys/count.go
  actions/access_keys/models.go
  actions/access_keys/search.go
  actions/admin/access_keys.go
  actions/admin/contact.go
  actions/admin/destinations.go
  actions/admin/models.go
  actions/admin/paymail_addresses.go
  actions/admin/transactions.go
  actions/admin/utxos.go
  actions/admin/xpubs.go
  actions/common/search_methods.go
  actions/contacts/models.go
  actions/contacts/search.go
  actions/destinations/count.go
  actions/destinations/models.go
  actions/destinations/search.go
  actions/transactions/count.go
  actions/transactions/models.go
  actions/transactions/search.go
  actions/utxos/count.go
  actions/utxos/models.go
  actions/utxos/search.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/model_contact.go
  engine/model_contact_test.go
  mappings/filter.go
  mappings/metadata.go
  models/filter/access_key_filter.go
  models/filter/contact_filter.go
  models/filter/destination_filter.go
  models/filter/generics.go
  models/filter/model_filter.go
  models/filter/models.go
  models/filter/paymail_filter.go
  models/filter/query_params.go
  models/filter/transaction_filter.go
  models/filter/utxo_filter.go
  models/filter/xpub_filter.go
Labels: tested

#606 chore/update-dependencies
  Dockerfile
  go.mod
  go.sum
Labels: tested

#605 fix(SPV-XXX): set callback host while running start.sh + default domain to be different than localhost
  config.example.yaml
  config/defaults.go
  start.sh
Labels: bug-P1, tested

#614 addressing dependencies issues
  go.mod
  go.sum
Labels: tested

#602 feat(SPV-802): implement extended pike capability
  actions/sharedconfig/get.go
  config/config.go
  config/defaults.go
  config/services.go
  engine/client_internal.go
  engine/client_options.go
  engine/examples/client/pike/main.go
  engine/go.mod
  engine/go.sum
  engine/model_destinations.go
  engine/model_destinations_test.go
  engine/model_transaction_config_test.go
  engine/paymail_service_provider.go
  engine/pike/pike.go
  engine/pike_service_provider.go
  go.mod
  go.sum
  server/server.go
Labels: tested

#615 feat(SPV-831): start.sh with no-run arg for mobile-start-sh
  start.sh
Labels: tested

#616 feat(spv-827) switch contacts capability from brfc temporary pike to brfc pike.invite
  engine/contact_service_test.go
  engine/go.mod
  engine/go.sum
  engine/paymail_servant.go
  go.mod
  go.sum
Labels: tested

#608 feat(SPV-815): refactor how the outputs in draft transaction are created
  engine/action_transaction.go
  engine/action_transaction_test.go
  engine/beef_tx_test.go
  engine/model_draft_transactions.go
  engine/model_draft_transactions_test.go
  engine/model_transactions_test.go
Labels: tested

#617 feat(SPV-000): define project name in start.sh to have reusable environment across all repositories
  docker-compose.yml
  start.sh
Labels: tested

#621 feat(SPV-xxx): update go-paymail version
  engine/go.mod
  engine/go.sum
  go.mod
  go.sum
Labels: tested

#620 feat(SPV-871): option to enable/disable callback + host validation
  config.example.yaml
  config/config.go
  config/defaults.go
  config/services.go
  config/services_test.go
  server/auth/middleware.go
  start.sh
Labels: feature, tested

#623 feat(SPV-839): get correct paymail when creating outputs
  engine/model_draft_transactions.go
Labels: tested

#624 feat(SPV-XXX): update dependencies and go version
  engine/go.mod
  engine/go.sum
  go.mod
  go.sum
  models/go.mod
Labels: tested

#625 feat(SPV-778): remove support for mAPI simplify code
  config.example.yaml
  config/config.go
  config/defaults.go
  config/nodes.go
  config/services.go
  config/validate_nodes.go
  config/validate_nodes_test.go
  engine/README.md
  engine/action_transaction.go
  engine/action_transaction_test.go
  engine/chainstate/arc_deafult.go
  engine/chainstate/broadcast.go
  engine/chainstate/broadcast_providers.go
  engine/chainstate/broadcast_test.go
  engine/chainstate/chainstate.go
  engine/chainstate/chainstate_test.go
  engine/chainstate/client.go
  engine/chainstate/client_options.go
  engine/chainstate/client_options_test.go
  engine/chainstate/client_test.go
  engine/chainstate/definitions.go
  engine/chainstate/interface.go
  engine/chainstate/merkle_root_test.go
  engine/chainstate/minercraft_default.go
  engine/chainstate/minercraft_init.go
  engine/chainstate/mock_const.go
  engine/chainstate/mock_minercraft.go
  engine/chainstate/requirements.go
  engine/chainstate/requirements_test.go
  engine/chainstate/transaction.go
  engine/chainstate/transaction_info.go
  engine/chainstate/transaction_test.go
  engine/client_options.go
  engine/client_options_test.go
  engine/go.mod
  engine/go.sum
  engine/mock_chainstate_test.go
  engine/model_bump.go
  engine/model_bump_test.go
  engine/model_draft_transactions_test.go
  engine/model_transaction_config_test.go
  engine/model_transactions.go
  engine/paymail_test.go
  engine/spv_wallet_engine_suite_test.go
  engine/spv_wallet_engine_test.go
  engine/sync_tx_service.go
  engine/tests/model_draft_transactions_test.json
  go.mod
  go.sum
Labels: feature, tested
