Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-11, with the labels that each got.

#756 feat(SPV-1158): record outline with OP_RETURN outputs
  engine/database/data.go
  engine/database/output.go
  engine/database/transaction.go
  engine/database/tx_status.go
  engine/transaction/errors/errors.go
  engine/transaction/outlines/transaction.go
  engine/transaction/outlines/transaction_outlines_service.go
  engine/transaction/record/interfaces.go
  engine/transaction/record/mock_test.go
  engine/transaction/record/op_return.go
  engine/transaction/record/record_outline.go
  engine/transaction/record/record_outline_test.go
  engine/transaction/record/service.go
  models/bsv/outpoint.go
Labels: tested, regression-tests

#766 feat(SPV-887): add address field to paymail_address response models
  engine/model_paymail_addresses.go
  mappings/paymail_address.go
  mappings/paymail_address_old.go
  models/paymail_address.go
  models/response/paymail_address.go
Labels: tested

#768 feat(SPV-680): standarize delete endpoints returns
  actions/access_keys/revoke.go
  actions/admin/contact.go
  actions/admin/webhooks.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: tested

#767 chore(SPV-1146): query error case to point out how search-by-array works
  internal/query/parse_test.go
Labels: chore, tested

#770 typo(SPV-XXX): fix error from create paymail address
  actions/admin/paymail_addresses_old.go
Labels: tested

#759 feat(SPV-1176): mock TX generator
  .golangci-lint.yml
  engine/chain/internal/ef/converter_test.go
  engine/chain/internal/ef/mock_txgetter_test.go
  engine/tester/cache.go
  engine/tester/fixtures/tx_fixtures.go
  engine/tester/fixtures/tx_fixtures_test.go
  engine/tester/fixtures/users_fixtures.go
  engine/transaction/errors/errors.go
  engine/transaction/record/mock_test.go
  engine/transaction/record/op_return.go
  engine/transaction/record/record_outline_test.go
Labels: tested

#769 ci(SPV-000): remove publishing on AWS repository until we agree where to publish.
  .github/workflows/manual-build-dockers.yml
  .github/workflows/release.yml
Labels: tested

#761 feat(SPV-1169) testabilities for record transaction outline
  engine/transaction/record/record_outline_test.go
  engine/transaction/record/testabilities/ability_record_outline.go
  engine/transaction/record/testabilities/assert_record_outline.go
  engine/transaction/record/testabilities/fixture_record_outline.go
  engine/transaction/record/testabilities/mock_broadcaster.go
  engine/transaction/record/testabilities/mock_repository.go
Labels: tested, regression-tests

#762 feat(SPV-1179): explicit GORM Automigrate
  config/config_to_options.go
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/client_options_test.go
  engine/client_test.go
  engine/datastore/client.go
  engine/datastore/client_options.go
  engine/datastore/client_options_test.go
  engine/datastore/client_test.go
  engine/datastore/interface.go
  engine/datastore/migrate.go
  engine/datastore/sql.go
  engine/datastore/where_mocks_test.go
  engine/db_model_transactions.go
  engine/definitions.go
  engine/examples/client/custom_models/custom_models.go
  engine/interface.go
  engine/model_access_keys.go
  engine/model_bump.go
  engine/model_contact.go
  engine/model_destinations.go
  engine/model_draft_transactions.go
  engine/model_paymail_addresses.go
  engine/model_transaction_config_test.go
  engine/model_transactions_test.go
  engine/model_utxos.go
  engine/model_webhook.go
  engine/model_xpubs.go
  engine/model_xpubs_test.go
  engine/models.go
  engine/paymail/paymail_test.go
  engine/spv_wallet_engine_suite_test.go
  engine/spv_wallet_engine_test.go
  engine/tester/database.go
  engine/tester/database_test.go
Labels: tested, regression-tests

#775 Feat(SPV-1008): new way of deleting paymails
  actions/admin/record.go
  engine/action_paymails.go
  engine/action_paymails_test.go
  engine/cron_job_definitions.go
  engine/datastore/errors.go
  engine/datastore/models.go
  engine/datastore/sql.go
  engine/datastore/where_mocks_test.go
  engine/model_access_keys.go
  engine/model_contact.go
  engine/model_destinations.go
  engine/model_draft_transactions.go
  engine/model_get.go
  engine/model_paymail_addresses.go
  engine/model_utxos.go
  engine/model_webhook.go
  engine/model_xpubs.go
  engine/tx_repository.go
Labels: tested, regression-tests

#776 feat(SPV-1185): expose contacts endpoints always - add limitation to pike_contacts_enabled flag
  actions/register.go
  config.example.yaml
  config/config.go
Labels: feature, tested, regression-tests

#778 feat(SPV-1058): database transaction inputs selector
  engine/database/testabilities/fixture_database.go
  engine/database/testabilities/user_utxo_fixture.go
  engine/database/user_utxos.go
  engine/datastore/sql.go
  engine/datastore/sqlite3extended/sqlite_extended.go
  engine/datastore/where_mocks_test.go
  engine/testabilities/fixture_engine.go
  engine/tester/fixtures/tx_const_fixtures.go
  engine/tester/tgorm/gorm_db_for_printing_sql.go
  engine/transaction/errors/errors.go
  engine/transaction/outlines/internal/inputs/inputs_query_composer.go
  engine/transaction/outlines/internal/inputs/selector.go
  engine/transaction/outlines/internal/inputs/selector_example_test.go
  engine/transaction/outlines/internal/inputs/selector_test.go
  engine/transaction/outlines/internal/inputs/testabilities/assertions_inputs_selector.go
  engine/transaction/outlines/internal/inputs/testabilities/fixture_inputs_selector.go
  engine/transaction/outlines/internal/inputs/testabilities/testability_inputs_selector.go
  go.mod
  go.sum
  models/transaction/bucket/bucket.go
Labels: tested

#783 chore(deps): bump go-paymail to 0.21.3
  go.mod
  go.sum
Labels: tested, regression-tests

#792 fix(SPV-1251): firewall bypassed when running start.sh
  docker-compose.yml
Labels: tested

#779 feat(SPV-1112): change models of Transaction and BUMP in BEEF hex creation to go-SDK Transaction and MerklePath
  conv/convert_primitives.go
  engine/beef_bump.go
  engine/beef_fixtures.go
  engine/beef_tx.go
  engine/beef_tx_bytes.go
  engine/beef_tx_sorting.go
  engine/beef_tx_sorting_test.go
  engine/beef_tx_test.go
  engine/model_bump.go
  engine/model_transactions.go
  engine/paymail_service_provider.go
Labels: tested, regression-tests
