Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-12, with the labels that each got.

#777 feat(SPV-1160): new record outline endpoint with actual repository for op_return txs
  actions/testabilities/fixture_spvwallet_application.go
  actions/transactions/internal/mapping/annotatedtx/annotated_tx_request_to_engine.go
  actions/transactions/outlines_endpoint_test.go
  actions/transactions/outlines_record.go
  actions/transactions/outlines_record_test.go
  actions/transactions/routes.go
  engine/client.go
  engine/client_internal.go
  engine/client_transaction.go
  engine/database/dao/transactions.go
  engine/database/data.go
  engine/database/models.go
  engine/database/output.go
  engine/database/tracked_transaction.go
  engine/database/transaction.go
  engine/definitions.go
  engine/interface.go
  engine/testabilities/fixture_arc.go
  engine/testabilities/fixture_engine.go
  engine/testabilities/testmode/db_mode.go
  engine/transaction/errors/errors.go
  engine/transaction/record/interfaces.go
  engine/transaction/record/record_outline.go
  engine/transaction/record/record_outline_test.go
  engine/transaction/record/testabilities/mock_broadcaster.go
  engine/transaction/record/testabilities/mock_repository.go
  server/handlers/manager.go
Labels: tested

#794 ci(SPV-1259): run regression tests without repository dispatch trigger
  .github/workflows/trigger-regression-tests.yml
  regression_tests/go.mod
Labels: tested, regression-tests

#793 feat(SPV-1249) paymail list & assert with JSON template
  actions/paymails/routes.go
  actions/paymails/search.go
  actions/paymails/search_test.go
  actions/register.go
  actions/testabilities/assert_spvwallet_application.go
  actions/users/get_test.go
  actions/users/routes_test.go
  actions/users/update_test.go
  actions/users/xpubs_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/tester/jsonrequire/funcs.go
  engine/tester/jsonrequire/matcher.go
  engine/tester/jsonrequire/matcher_test.go
  engine/tester/jsonrequire/placeholders.go
  engine/tester/jsonrequire/xpath.go
  models/filter/paymail_filter.go
Labels: tested

#800 fix(SPV-1069) fix lint errors for "models" package
  models/bsv/satoshis.go
  models/contact.go
  models/filter/access_key_filter.go
  models/filter/contact_filter.go
  models/filter/destination_filter.go
  models/filter/generics.go
  models/filter/paymail_filter.go
  models/filter/search_params.go
  models/filter/transaction_admin_filter.go
  models/filter/transaction_filter.go
  models/filter/utxo_filter.go
  models/filter/xpub_filter.go
  models/optional/optional.go
  models/request/opreturn/data_type.go
  models/request/opreturn/output.go
  models/request/paymail/paymail_output.go
  models/request/transaction_specification.go
  models/request/transaction_specification_json.go
  models/response/contact.go
  models/swagger/access_key_params.go
Labels: chore, tested

#795 feat(SPV-1225): admin confirm contacts
  actions/admin/contact.go
  actions/admin/routes.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_contact.go
  engine/interface.go
  engine/spverrors/definitions.go
  models/contact.go
Labels: tested, regression-tests

#808 fix(SPV-1294): fix local operator regression tests
  actions/admin/paymail_addresses_old.go
  engine/spverrors/definitions.go
  regression_tests/operator.go
  regression_tests/utils.go
Labels: tested, regression-tests

#807 feat(SPV-1284): add admin method to create contact between two parties
  actions/admin/contact.go
  actions/admin/models.go
  actions/admin/routes.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_contact.go
  engine/contact_service_test.go
  engine/interface.go
  engine/spverrors/definitions.go
Labels: feature, tested, regression-tests

#815 feat(SPV-1214): add contact filter for admin
  actions/admin/contact.go
  actions/admin/contact_old.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  models/contact.go
  models/filter/contact_admin_filter.go
  models/filter/contact_admin_filter_test.go
  models/filter/models.go
Labels: tested, regression-tests

#816 fix(SPV-000): enhance DefaultsIfNil to check for empty QueryParams
  actions/admin/contact_old.go
  actions/contacts/search.go
  models/filter/generics.go
Labels: tested, regression-tests

#822 fix(SPV-000): update xpubid to xpubId in admin filters for consistency
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  models/filter/contact_admin_filter.go
  models/filter/transaction_admin_filter.go
Labels: tested

#821 feat(SPV-1316) type42 derivation
  engine/keys/type42/derivation.go
  engine/keys/type42/destination.go
  engine/keys/type42/destination_test.go
  engine/keys/type42/errors.go
  engine/keys/type42/pki.go
  engine/keys/type42/pki_test.go
  engine/keys/type84/linking_key.go
  engine/keys/type84/linking_key_test.go
  engine/pike/pike.go
Labels: feature, tested

#825 ci(SPV-1285): add to workflow lint & test models package
  .github/workflows/run-tests.yml
Labels: tested

#829 feat(SPV-1300): experimental new tx flow feature flag
  actions/access_keys/access_keys_test.go
  actions/admin/admin_test.go
  actions/base/base_test.go
  actions/contacts/contacts_test.go
  actions/destinations/destination_test.go
  actions/register.go
  actions/transactions/outlines_endpoint_test.go
  actions/transactions/outlines_record_test.go
  actions/transactions/routes.go
  actions/transactions/transaction_test.go
  actions/utxos/utxo_test.go
  config/config.go
  config/config_to_options.go
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/paymail/paymail_service_provider.go
  engine/testabilities/fixture_configopts.go
  engine/testabilities/fixture_engine.go
  server/handlers/manager.go
  server/server.go
Labels: tested, regression-tests
