Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-01, with the labels that each got.

#392 chore(BUX-431) Configure & select `mapi` or `arc` with arc-gorillapool as default
  config.example.yaml
  config/config.go
  config/defaults.go
  config/nodes.go
  config/services.go
  config/validate_nodes.go
  config/validate_nodes_test.go
  go.mod
  go.sum
Labels: update

#393 fix(BUX-000): replace default xpub to match defaults in other repos
  README.md
  config.example.yaml
  config/defaults.go
Labels: bug-P3

#397 chore(BUX-456): config validation first
  cmd/server/main.go
  config/config_test.go
  config/validate.go
Labels: update

#398 Feat(BUX-000): Adds flag for image rebuilding purposes to quickstart script
  README.md
  start-bux-server.sh
Labels: feature

#400 feat(BUX-000): bux version update
  cmd/server/main.go
  config/config.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
Labels: feature

#401 fix(BUX-460): change pprof methods to get in replace of patch
  actions/base/routes.go
  actions/base/routes_test.go
Labels: bug-P3

#404 feat(BUX-449): change release flow to also build docker image
  .dockerignore
  .github/workflows/release.yml
  .goreleaser.yml
  README.md
  release/Dockerfile
Labels: feature

#405 fix(BUX-449): docker image cannot be run
  .github/workflows/release.yml
  release/Dockerfile
  release/entrypoint.sh
Labels: bug-P3

#403 fix(BUX-461) fee quotes for both arc and mAPI with user defined fee quote
  config.example.yaml
  config/config.go
  config/defaults.go
  config/services.go
  config/validate.go
  config/validate_nodes.go
  config/validate_nodes_test.go
  go.mod
  go.sum
Labels: bug-P3

#402 Feat(BUX-417): remove monitor, itc flag
  actions/destinations/create.go
  config.example.yaml
  config/config.go
  config/defaults.go
  config/services.go
  config/validate.go
  config/validate_nodes.go
  config/validate_nodes_test.go
  go.mod
  go.sum
  graph/schema.resolvers.go
  mappings/destination.go
Labels: feature

#408 feat(BUX-417): remove unused env
  config/config.go
  config/defaults.go
  config/services.go
  go.mod
  go.sum
Labels: feature

#410 chore: Release v0.12.0
  cmd/server/main.go
  config/config.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: update

#415 docs(BUX-442): updates readme and code standards
  .github/CODE_STANDARDS.md
  README.md
Labels: documentation

#422 feat(BUX-515): removed PaymailConfig.Enabled
  cmd/server/main.go
  config.example.yaml
  config/config.go
  config/config_test.go
  config/defaults.go
  config/services.go
  config/validate_paymail.go
  config/validate_paymail_test.go
  server/server.go
Labels: feature

#423 feat(BUX-512): checking pulse connection on startup & enabled Beef as default
  cmd/server/main.go
  config.example.yaml
  config/check_pulse.go
  config/defaults.go
Labels: feature

#419 chore(BUX-506): update bux-server config description
  README.md
  config.example.yaml
Labels: feature

#429 feat(BUX-525): remove graphql
  Makefile
  README.md
  actions/graphql/graphql.go
  actions/graphql/routes.go
  cmd/server/main.go
  config/config.go
  config/defaults.go
  config/graphql.go
  go.mod
  go.sum
  gqlgen.yml
  gqlgen/gqlgen.go
  gqlgen/helpers.go
  gqlgen/int.go
  gqlgen/null.go
  gqlgen/uint.go
  graph/admin.graphqls
  graph/admin.resolvers.go
  graph/generated/generated.go
  graph/graph.go
  graph/model/models_gen.go
  graph/resolver.go
  graph/schema.graphqls
  graph/schema.resolvers.go
  server/server.go
Labels: feature

#440 chore: bump bux ver 0.14.1 -> 0.14.2
  config/defaults.go
  config/services.go
  go.mod
  go.sum
Labels: update
