Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-09, with the labels that each got.

#660 feat(SPV-834): new utxo API and deprecation of destinations API
  actions/access_keys/search.go
  actions/destinations/count.go
  actions/destinations/create.go
  actions/destinations/get.go
  actions/destinations/search.go
  actions/destinations/update.go
  actions/utxos/count.go
  actions/utxos/get.go
  actions/utxos/routes.go
  actions/utxos/routes_test.go
  actions/utxos/search.go
  actions/utxos/utxo_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_utxo.go
  engine/interface.go
  engine/model_utxos.go
  mappings/utxo.go
  server/server.go
Labels: refactor, tested

#680 feat(SPV-897): introduce correct path and command for js regression tests
  regression_tests/operator.go
Labels: tested

#686 feat(SPV-938): update go-broadcast-client with the newest go-sdk kit
  go.mod
  go.sum
Labels: dependencies, tested

#687 feat(SPV-1020): create draft transaction handling OP RETURN output;
  engine/spverrors/definitions.go
  engine/transaction/annotation.go
  engine/transaction/draft/create_draft.go
  engine/transaction/draft/create_draft_test.go
  engine/transaction/draft/create_op_return_draft_test.go
  engine/transaction/draft/outputs/op_return.go
  engine/transaction/draft/outputs/spec.go
  engine/transaction/draft/transaction.go
  engine/transaction/draft/transaction_spec.go
  engine/transaction/errors/errors.go
  go.mod
  mappings/draft/to_engine.go
  mappings/draft/to_engine_test.go
  models/request/draft_transaction.go
  models/request/draft_transaction_json.go
  models/request/draft_transaction_test.go
  models/request/opreturn/data_type.go
  models/request/opreturn/output.go
Labels: tested

#692 feat(SPV-1026): removed broadcast cronjob and updated transaction strategies
  engine/action_transaction.go
  engine/action_transaction_test.go
  engine/cron_job_declarations.go
  engine/cron_job_definitions.go
  engine/definitions.go
  engine/model_sync_transactions.go
  engine/model_sync_transactions_test.go
  engine/model_transactions_test.go
  engine/paymail_service_provider.go
  engine/process_p2p_transaction.go
  engine/record_tx.go
  engine/record_tx_strategy_external_incoming_tx.go
  engine/record_tx_strategy_internal_incoming_tx.go
  engine/record_tx_strategy_outgoing_tx.go
  engine/sync_tx_repository.go
  engine/sync_tx_service.go
  engine/sync_tx_service_test.go
  engine/tx_service.go
  models/sync_transaction.go
Labels: tested

#683 feat(SPV-996): search endpoint transactions and contacts
  actions/contacts/search.go
  actions/transactions/count.go
  actions/transactions/search.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_transaction.go
  engine/datastore/where_builder.go
  engine/datastore/where_test.go
  internal/query/parse_test.go
  mappings/search.go
  mappings/transaction.go
  models/filter/search_params.go
  models/filter/transaction_filter.go
Labels: tested

#696 feat(SPV-1034): remove unnecessary SyncResult
  engine/model_sync_results.go
  engine/model_sync_transactions.go
  engine/model_sync_transactions_test.go
  engine/paymail.go
  engine/process_p2p_transaction.go
  engine/record_tx.go
  engine/sync_tx_service.go
  models/sync_result.go
  models/sync_transaction.go
Labels: tested

#679 fix(SPV-000): remove job run, move if statement, adjust name
  .github/workflows/trigger-regression-tests.yml
Labels: tested

#698 refactor(SPV-1020): change draft.Create into method on draft service
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/client_transaction.go
  engine/interface.go
  engine/transaction/draft/create_draft_test.go
  engine/transaction/draft/create_op_return_draft_test.go
  engine/transaction/draft/draft_service.go
  engine/transaction/draft/inteface.go
  go.sum
Labels: tested

#703 refactor(SPV-1038): remove unused (and obsolete) query transactions fastest
  engine/chainstate/chainstate.go
  engine/chainstate/chainstate_test.go
  engine/chainstate/interface.go
  engine/chainstate/transaction.go
  engine/chainstate/transaction_test.go
Labels: tested

#702 feat(SPV-1056): add handling paymail output in new transaction drafts
  engine/paymail/errors/errors.go
  engine/paymail/paymail_service_client.go
  engine/paymail/paymail_service_client_interface.go
  engine/paymail/paymail_test.go
  engine/tester/paymailmock/mock_capability.go
  engine/tester/paymailmock/mock_capability_factories.go
  engine/tester/paymailmock/mock_paymail_client.go
  engine/tester/paymailmock/mock_paymail_host_responses.go
  engine/transaction/annotation.go
  engine/transaction/draft/create_paymail_draft_test.go
  engine/transaction/draft/draft_service.go
  engine/transaction/draft/evaluation/context.go
  engine/transaction/draft/evaluation/interface.go
  engine/transaction/draft/outputs/op_return.go
  engine/transaction/draft/outputs/paymail.go
  engine/transaction/draft/outputs/spec.go
  engine/transaction/draft/transaction_spec.go
  engine/transaction/errors/errors.go
  mappings/draft/to_engine.go
  mappings/draft/to_engine_test.go
  models/bsv/satoshis.go
  models/optional/optional.go
  models/request/draft_transaction_json.go
  models/request/draft_transaction_test.go
  models/request/paymail/paymail_output.go
Labels: tested

#701 feat(SPV-1038): decouple sync job from SyncTx
  actions/transactions/broadcast_callback.go
  engine/action_transaction.go
  engine/action_transaction_test.go
  engine/chainstate/chainstate.go
  engine/chainstate/transaction.go
  engine/chainstate/transaction_info.go
  engine/cron_job_declarations.go
  engine/cron_job_definitions.go
  engine/datastore/client.go
  engine/datastore/interface.go
  engine/db_model_transactions.go
  engine/examples/client/custom_cron/custom_cron.go
  engine/interface.go
  engine/model_bump.go
  engine/model_sync_transactions.go
  engine/model_sync_transactions_test.go
  engine/model_transactions.go
  engine/paymail_service_provider.go
  engine/process_p2p_transaction.go
  engine/record_tx_strategy_external_incoming_tx.go
  engine/record_tx_strategy_internal_incoming_tx.go
  engine/record_tx_strategy_outgoing_tx.go
  engine/spverrors/definitions.go
  engine/sync_tx_repository.go
  engine/sync_tx_service.go
  engine/sync_tx_service_test.go
  engine/tx_broadcast.go
  engine/tx_service.go
  engine/tx_status.go
  engine/tx_sync_task.go
  mappings/transaction.go
  models/errors.go
  models/errors_test.go
Labels: tested

#705 feat(SPV-1021): add config for block header service
  config.example.yaml
  config/config.go
  config/defaults.go
  config/validate.go
  config/validate_bhs.go
  config/validate_bhs_test.go
Labels: tested, regression-tests

#709 fix(SPV-1030): regression tests tweaks
  .github/workflows/trigger-regression-tests.yml
  engine/record_tx_strategy_outgoing_tx.go
  regression_tests/operator.go
  regression_tests/utils.go
Labels: tested

#700 feat(SPV-1048): fixed metadata editing
  actions/transactions/update.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_destination_test.go
  engine/action_paymails_test.go
  engine/action_xpub_test.go
  engine/models_internal.go
Labels: tested

#707 feat(SPV-1072): unfold and log wrapped & joined errors
  cmd/main.go
  engine/spverrors/http_response.go
  engine/spverrors/unfold.go
  engine/spverrors/unfold_test.go
  logging/error_marshal.go
Labels: tested, regression-tests

#712 feat(SPV-1071): handle sender paymail in paymail outputs
  engine/client.go
  engine/client_internal.go
  engine/model_transaction_config_test.go
  engine/paymail/paymail_test.go
  engine/paymail/testabilities/test_paymail_service_client.go
  engine/paymailaddress/paerrors/errors.go
  engine/paymailaddress/paymail_address_service.go
  engine/paymailaddress/paymail_address_service_interface.go
  engine/paymailaddress/testabilities/ability_paymail_address_service.go
  engine/spverrors/definitions.go
  engine/tester/fixtures/paymail.go
  engine/tester/logger.go
  engine/tester/paymailmock/mock_paymail_client.go
  engine/tester/paymailmock/paymail_service_fixture.go
  engine/transaction/annotation.go
  engine/transaction/draft/create_draft_test.go
  engine/transaction/draft/create_op_return_draft_test.go
  engine/transaction/draft/create_paymail_draft_test.go
  engine/transaction/draft/draft_service.go
  engine/transaction/draft/evaluation/context.go
  engine/transaction/draft/evaluation/interface.go
  engine/transaction/draft/outputs/op_return.go
  engine/transaction/draft/outputs/paymail.go
  engine/transaction/draft/testabilities/ability_draft_transaction.go
  engine/transaction/draft/transaction_spec.go
  engine/transaction/errors/errors.go
  mappings/draft/to_engine.go
  mappings/draft/to_engine_test.go
  models/request/draft_transaction_test.go
Labels: tested, regression-tests

#713 feat(SPV-1076) single ARC configuration
  config.example.yaml
  config/config.go
  config/defaults.go
  config/nodes.go
  config/services.go
  config/services_test.go
  config/validate.go
  config/validate_nodes.go
  config/validate_nodes_test.go
  server/middleware/callbacktoken_middleware.go
  start.sh
Labels: tested, regression-tests

#714 test(SPV-1071): add custom fluent assertions for draft transactions
  .golangci-lint.yml
  engine/transaction/draft/create_draft_test.go
  engine/transaction/draft/create_op_return_draft_test.go
  engine/transaction/draft/create_paymail_draft_test.go
  engine/transaction/draft/testabilities/ability_draft_transaction.go
  engine/transaction/draft/testabilities/assert_draft_transaction.go
  engine/transaction/draft/testabilities/fixture_draft_transaction.go
Labels: test, tested

#711 feat(SPV-1021): add connection to bhs merkleroots endpoint
  actions/merkleroots/bhs_error_response.go
  actions/merkleroots/errors.go
  actions/merkleroots/get.go
  actions/merkleroots/get_merkleroots_from_bhs.go
  actions/merkleroots/merkleroots_test.go
  actions/merkleroots/routes.go
  actions/merkleroots/routes_test.go
  actions/register.go
Labels: tested, regression-tests
