Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-03, with the labels that each got.

#483 feat(BUX-596): change code owners
  .github/CODEOWNERS
Labels: tested

#484 feat(BUX-595) update start.sh after renaming
  README.md
  docker-compose.yml
  start.sh
Labels: tested

#472 Bux 396/endpoint for creating contact
  actions/contacts/contacts.go
  actions/contacts/contacts_test.go
  actions/contacts/create.go
  actions/contacts/models.go
  actions/contacts/routes.go
  actions/contacts/routes_test.go
  config/config.go
  config/defaults.go
  engine/action_contact.go
  engine/client_options_test.go
  engine/definitions.go
  engine/errors.go
  engine/examples/client/broadcast_miners/broadcast_miners.go
  engine/examples/client/chainstate/chainstate.go
  engine/examples/client/custom_rates/custom_rates.go
  engine/examples/client/custom_user_agent/custom_user_agent.go
  engine/examples/client/debugging/debugging.go
  engine/examples/client/encryption/encryption.go
  engine/examples/client/logging/logging.go
  engine/interface.go
  engine/model_contact.go
  engine/model_contact_status.go
  engine/model_contact_test.go
  engine/models_test.go
  engine/utils/scripts_test.go
  mappings/contact.go
  models/contact.go
  server/server.go
Labels: tested

#488 ci(BUX-616): release workflow for engine and models libraries
  .github/workflows/release.yml
Labels: tested

#494 chore(BUX-640): handle domains in start.sh
  docker-compose.yml
  start.sh
Labels: chore, tested

#495 chore(BUX-628): add admin panel to start.sh
  README.md
  docker-compose.yml
  start.sh
Labels: tested

#496 feat(BUX-641) Shared Config
  actions/admin/routes.go
  actions/admin/shared_config.go
  actions/base/base_test.go
  actions/base/routes.go
  actions/base/routes_test.go
  models/shared_config.go
  server/server.go
Labels: tested

#503 chore(BUX-641): remove unneeded config param for frontend in start.sh
  docker-compose.yml
Labels: tested

#501 chore(000): clean test logs to make them possible to read
  actions/access_keys/access_keys_test.go
  actions/admin/admin_test.go
  actions/base/base_test.go
  actions/contacts/contacts_test.go
  actions/destinations/destination_test.go
  actions/transactions/transaction_test.go
  actions/utxos/utxo_test.go
  actions/xpubs/xpubs_test.go
  config/config_test.go
  config/load.go
  server/auth/middleware.go
  server/server_test.go
  tests/tests.go
Labels: tested

#490 Bux-398/ get waiting contacts
  actions/contacts/contacts.go
  actions/contacts/create.go
  actions/contacts/routes.go
  actions/contacts/routes_test.go
  actions/contacts/search.go
  engine/action_contact.go
  engine/definitions.go
  engine/errors.go
  engine/interface.go
  engine/model_contact.go
  engine/model_contact_test.go
  engine/models_test.go
Labels: tested

#497 feat(bux-399): Confirm contact
  actions/contacts/models.go
  actions/contacts/routes.go
  actions/contacts/update.go
  engine/action_contact.go
  engine/definitions.go
  engine/interface.go
  engine/model_contact.go
  engine/model_contact_test.go
Labels: tested

#492 feat(BUX-576) request metrics
  engine/metrics/interface.go
  metrics/collector.go
  metrics/gin_middleware.go
  metrics/global.go
  metrics/metrics.go
  metrics/naming.go
  metrics/request.go
  server/server.go
Labels: tested

#493 feat(BUX-608): update swagger
  actions/access_keys/count.go
  actions/access_keys/create.go
  actions/access_keys/get.go
  actions/access_keys/models.go
  actions/access_keys/revoke.go
  actions/access_keys/search.go
  actions/admin/access_keys.go
  actions/admin/destinations.go
  actions/admin/models.go
  actions/admin/paymail_addresses.go
  actions/admin/record.go
  actions/admin/shared_config.go
  actions/admin/stats.go
  actions/admin/status.go
  actions/admin/transactions.go
  actions/admin/utxos.go
  actions/admin/xpubs.go
  actions/contacts/create.go
  actions/contacts/models.go
  actions/contacts/search.go
  actions/contacts/update.go
  actions/destinations/count.go
  actions/destinations/create.go
  actions/destinations/get.go
  actions/destinations/models.go
  actions/destinations/search.go
  actions/destinations/update.go
  actions/methods.go
  actions/transactions/broadcast_callback.go
  actions/transactions/count.go
  actions/transactions/get.go
  actions/transactions/models.go
  actions/transactions/new.go
  actions/transactions/record.go
  actions/transactions/search.go
  actions/transactions/update.go
  actions/utxos/count.go
  actions/utxos/get.go
  actions/utxos/models.go
  actions/utxos/search.go
  actions/xpubs/get.go
  actions/xpubs/update.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  models/access_key.go
  models/common/model.go
  models/contact.go
  models/destination.go
  models/draft_transaction.go
  models/fee_unit.go
  models/paymail_address.go
  models/shared_config.go
  models/transaction.go
  models/transaction_config.go
  models/utxo.go
  models/xpub.go
  server/server.go
Labels: tested

#508 feat(BUX-645): adjust xpub parameter
  actions/admin/models.go
  actions/admin/paymail_addresses.go
Labels: feature, tested

#511 fix(BUX-000): panic when pike_enabled
  server/server.go
Labels: tested

#499 fix(BUX-644): return stable pub key from PKI capability
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_contact.go
  engine/action_paymails.go
  engine/action_paymails_test.go
  engine/action_transaction.go
  engine/client_options.go
  engine/client_options_test.go
  engine/locks.go
  engine/model_destinations.go
  engine/model_destinations_test.go
  engine/model_paymail_addresses.go
  engine/model_paymail_addresses_test.go
  engine/model_transaction_config_test.go
  engine/model_xpubs.go
  engine/paymail_default_service_provider_test.go
  engine/paymail_service_provider.go
  mappings/destination.go
  mappings/paymail_address.go
  models/destination.go
  models/paymail_address.go
  models/xpub.go
Labels: bug-P2, tested

#516 fix(BUX-000): fix postgres migration
  engine/model_paymail_addresses.go
  engine/model_xpubs.go
Labels: tested

#491 feat(BUX-395) pike capability
  actions/contacts/create.go
  actions/contacts/models.go
  actions/contacts/routes.go
  actions/contacts/routes_test.go
  actions/contacts/upsert.go
  config/services.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_contact.go
  engine/client_internal.go
  engine/client_options.go
  engine/contact_service_test.go
  engine/definitions.go
  engine/errors.go
  engine/go.mod
  engine/go.sum
  engine/interface.go
  engine/metrics/metrics.go
  engine/model_contact.go
  engine/model_contact_status.go
  engine/model_contact_test.go
  engine/model_paymail_addresses.go
  engine/model_paymail_addresses_test.go
  engine/paymail.go
  engine/paymail_default_service_provider_test.go
  engine/paymail_mocks_test.go
  engine/paymail_servant.go
  engine/paymail_service_provider.go
  engine/paymail_test.go
  engine/spv_wallet_engine_test.go
  engine/utils.go
  go.mod
  go.sum
  mappings/contact.go
  models/contact.go
Labels: feature, tested

#522 fix(BUX-000): duplicated metric name
  engine/metrics/metrics.go
  engine/metrics/naming.go
Labels: tested

#512 feat(BUX-397): acceptance and rejection of establishing contacts
  actions/contacts/accept.go
  actions/contacts/reject.go
  actions/contacts/routes.go
  actions/contacts/routes_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_contact.go
  engine/action_contact_test.go
  engine/action_paymails.go
  engine/definitions.go
  engine/interface.go
  engine/model_contact.go
  engine/model_contact_status.go
  mappings/contact.go
Labels: tested
