Repository bitcoin-sv/spv-wallet, pull requests merged in 2024-02, with the labels that each got.

#437 feat(BUX-516): add possibility to run Pulse; use the same script as in bux-wallet-frontend.
  README.md
  docker-compose.yml
  start-bux-server.sh
  start.sh
Labels: feature

#439 feat(BUX-368): Arc callbacks
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  actions/middleware.go
  actions/transactions/broadcast_callback.go
  actions/transactions/routes.go
  cmd/server/main.go
  config.example.yaml
  config/config.go
  config/defaults.go
  config/services.go
  dictionary/dictionary.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: feature

#446 feat(BUX-500): add DeploymentID to bux-server configuration
  .github/workflows/run-tests.yml
  config.example.yaml
  config/config.go
  config/defaults.go
  config/nodes.go
  go.mod
  go.sum
Labels: feature

#459 feat(BUX-000): logger fix for kibana
  logging/logging.go
Labels: tested

#443 Release candidate v1.1.0
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  actions/admin/block_headers.go
  actions/admin/routes.go
  actions/destinations/create.go
  actions/middleware.go
  actions/transactions/broadcast_callback.go
  actions/transactions/routes.go
  cmd/server/main.go
  config.example.yaml
  config/config.go
  config/defaults.go
  config/services.go
  dictionary/dictionary.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  mappings/destination.go
  metrics/collector.go
  metrics/global.go
  metrics/metrics.go
  metrics/naming.go
  server/server.go
Labels: tested

#471 chore(BUX-586, 601, 602): inner PR for PR changes
  README.md
  config.example.yaml
  config/config.go
  config/defaults.go
  config/load.go
  config/load_test.go
  config/services.go
  config/task_manager.go
  engine/.editorconfig
  engine/.gitattributes
  engine/.gitignore
  engine/.golangci.yml
  engine/.yamllint.yml
  engine/LICENSE
  engine/Makefile
  engine/README.md
  go.mod
  models/.editorconfig
  models/.gitattributes
  models/.gitignore
  models/.golangci.yml
  models/.yamllint.yml
  models/LICENSE
  models/Makefile
  spv_wallet.go
Labels: update

#475 feat(598): broadcast in EF if possible
  engine/action_transaction.go
  engine/chainstate/broadcast.go
  engine/chainstate/broadcast_providers.go
  engine/chainstate/broadcast_test.go
  engine/chainstate/chainstate.go
  engine/chainstate/interface.go
  engine/chainstate/transaction.go
  engine/ef_tx.go
  engine/mock_chainstate_test.go
  engine/model_transactions.go
  engine/model_transactions_test.go
  engine/paymail_service_provider.go
  engine/record_tx.go
  engine/record_tx_strategy_external_incoming_tx.go
  engine/record_tx_strategy_internal_incoming_tx.go
  engine/record_tx_strategy_outgoing_tx.go
  engine/sync_tx_service.go
Labels: tested

#479 BUX-623/ Postgresql engine
  config.example.yaml
Labels: tested
