Repository bitcoin-sv/spv-wallet, pull requests merged in 2025-01, with the labels that each got.

#835 feat(SPV-1345): get webhooks
  actions/admin/routes.go
  actions/admin/webhooks.go
  actions/admin/webhooks_old.go
  actions/admin/webhooks_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/client.go
  engine/datastore/sql.go
  engine/testabilities/fixture_configopts.go
Labels: tested

#834 feat(SPV-1298): utxo endpoint tests
  actions/utxos/routes_test.go
  actions/utxos/search_test.go
  actions/utxos/utxo_test.go
Labels: test, tested

#836 feat(SPV-1347): extend timout to allow user send funds from external wallet
  regression_tests/operator.go
  regression_tests/utils.go
Labels: chore, tested

#839 feat(SPV-1337): paymail capabilities test
  actions/paymailserver/incoming_paymail_tx_test.go
  actions/paymailserver/register.go
  actions/paymailserver/stateless_capabilities_test.go
  actions/testabilities/assert_spvwallet_application.go
  actions/testabilities/fixture_spvwallet_application.go
  engine/testabilities/fixture_block_header_service.go
  engine/testabilities/fixture_configopts.go
  engine/tester/fixtures/tx_fixtures.go
  engine/tester/fixtures/tx_fixtures_test.go
  engine/tester/fixtures/users_fixtures.go
  engine/tester/jsonrequire/funcs.go
  engine/tester/jsonrequire/getter.go
  engine/transaction/record/record_outline_test.go
  server/server.go
Labels: tested

#843 fix(SPV-1357): webhook tests
  engine/notifications/webhook_manager.go
Labels: tested

#842 feat(SPV-1295): testabilities for contacts admin
  engine/action_contact.go
  engine/contact/contact_test.go
  engine/contact/testabilities/ability_contact.go
  engine/contact/testabilities/assert_contact.go
  engine/contact/testabilities/fixture_contact.go
  engine/contact_service_test.go
  engine/testabilities/fixture_engine.go
  engine/tester/fixtures/users_fixtures.go
  engine/tester/paymailmock/mock_capability.go
  engine/tester/paymailmock/mock_capability_factories.go
Labels: tested

#850 bug(SPV-1342) admin_endpoint_for_paginated_response_doesnt_map_status_and_direction_in_response
  actions/admin/transactions.go
  engine/model_transactions.go
  engine/tx_status.go
  mappings/transaction.go
Labels: test, tested, regression-tests

#849 feat(SPV-1318): fix displaying deleted paymails
  engine/action_paymails.go
  engine/model_paymail_addresses.go
Labels: tested, regression-tests

#828 feat(SPV-1248) add domain check for paymail entry
  actions/admin/paymail_addresses.go
  actions/admin/paymail_addresses_old.go
  actions/admin/paymail_addresses_test.go
  engine/spverrors/definitions.go
Labels: chore, tested

#851 feat(SPV-1377): feat parse query
  internal/query/parse.go
  models/filter/access_key_filter.go
  models/filter/contact_admin_filter.go
  models/filter/contact_filter.go
  models/filter/destination_filter.go
  models/filter/paymail_filter.go
  models/filter/transaction_admin_filter.go
  models/filter/transaction_filter.go
  models/filter/utxo_filter.go
  models/filter/xpub_filter.go
Labels: tested, regression-tests

#852 feat(SPV-1386): address resolution capability
  actions/paymailserver/incoming_paymail_tx_test.go
  actions/paymailserver/old_incoming_paymail_tx_test.go
  engine/paymail/paymail_service_provider.go
Labels: tested

#853 bug(SPV-1266, SPV-1290) Admin_endpoints_have_incorrect_params_in_swagger_documentation and APIVersion_Swagger
  actions/admin/access_keys.go
  actions/admin/access_keys_old.go
  actions/admin/contact.go
  actions/admin/contact_old.go
  actions/admin/destinations.go
  actions/admin/helpers.go
  actions/admin/paymail_addresses.go
  actions/admin/paymail_addresses_old.go
  actions/admin/record.go
  actions/admin/transactions.go
  actions/admin/transactions_old.go
  actions/admin/utxos.go
  actions/admin/utxos_old.go
  actions/admin/webhooks_old.go
  actions/admin/xpubs.go
  actions/admin/xpubs_old.go
  actions/base/routes.go
  config/load_config_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  server/handlers/manager.go
Labels: tested, regression-tests

#854 feat(SPV-1341): change delete paymail endpoint to be more restful
  actions/admin/paymail_addresses.go
  actions/admin/paymail_addresses_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  engine/action_paymails.go
  engine/interface.go
Labels: tested, regression-tests

#857 feat(SPV-1387, SPV-1396): replace estimated unlocking script size with estimated input size; rename UsersUTXO
  engine/database/models.go
  engine/database/repository/users.go
  engine/database/testabilities/fixture_database.go
  engine/database/testabilities/user_utxo_fixture.go
  engine/database/tracked_transaction.go
  engine/database/user_utxos.go
  engine/tester/fixtures/tx_const_fixtures.go
  engine/tester/fixtures/tx_fixtures_test.go
  engine/transaction/outlines/internal/inputs/inputs_query_composer.go
  engine/transaction/outlines/internal/inputs/selector.go
  engine/transaction/outlines/internal/inputs/selector_example_test.go
  engine/transaction/outlines/internal/inputs/selector_test.go
  engine/transaction/outlines/internal/inputs/testabilities/assertions_inputs_selector.go
Labels: refactor, tested

#867 task(SPV-1423) [spv-wallet] [spv-wallet-mobile-backend] start.sh adjust scripts after api migration
  docker-compose.yml
  start.sh
Labels: tested, regression-tests

#861 feat(SPV-1029): allow camelcase in sortby param
  mappings/search.go
Labels: automerge, tested, regression-tests

#856 feat(SPV-1392): add & get user as admin
  actions/v2/admin/errors/errors.go
  actions/v2/admin/internal/mapping/paymail.go
  actions/v2/admin/internal/mapping/user.go
  actions/v2/admin/register.go
  actions/v2/admin/users/create.go
  actions/v2/admin/users/create_test.go
  actions/v2/admin/users/get.go
  actions/v2/admin/users/paymail_add.go
  actions/v2/admin/users/paymail_add_test.go
  actions/v2/admin/users/routes.go
  actions/v2/register.go
  config/config.go
  engine/client.go
  engine/client_internal.go
  engine/database/address.go
  engine/database/paymail.go
  engine/database/repository/addresses.go
  engine/database/repository/paymails.go
  engine/database/repository/users.go
  engine/database/tracked_transaction.go
  engine/database/user.go
  engine/database/user_utxos.go
  engine/interface.go
  engine/paymail/interface.go
  engine/paymail/interfaces.go
  engine/paymail/paymail_service_provider.go
  engine/testabilities/fixture_engine.go
  engine/tester/jsonrequire/funcs.go
  engine/transaction/record/tx_flow.go
  engine/utils/map_slice.go
  engine/v2/addresses/addresses_service.go
  engine/v2/addresses/addressesmodels/address.go
  engine/v2/addresses/interface.go
  engine/v2/paymails/interface.go
  engine/v2/paymails/paymails_service.go
  engine/v2/paymails/paymailsmodels/paymail.go
  engine/v2/users/interface.go
  engine/v2/users/users_service.go
  engine/v2/users/usersmodels/paymail.go
  engine/v2/users/usersmodels/user.go
  models/bsv/custom_instructions.go
  models/request/adminrequest/paymail.go
  models/request/adminrequest/user.go
  models/response/adminresponse/paymail.go
  models/response/adminresponse/user.go
  server/handlers/manager.go
  server/middleware/auth_v2_middlware.go
  server/reqctx/usercontext.go
Labels: feature, tested, regression-tests

#866 refactor(SPV-1404): adjust tx outline to type42 changes.
  actions/transactions/internal/mapping/outline/outline_request_to_engine.go
  actions/transactions/outlines.go
  actions/transactions/outlines_endpoint_test.go
  engine/client.go
  engine/client_internal.go
  engine/database/repository/paymails.go
  engine/paymail/interface.go
  engine/paymail/paymail_service_provider.go
  engine/paymailaddress/paymail_address_service.go
  engine/paymailaddress/paymail_address_service_interface.go
  engine/paymailaddress/testabilities/ability_paymail_address_service.go
  engine/tester/fixtures/users_fixtures.go
  engine/transaction/annotation.go
  engine/transaction/errors/errors.go
  engine/transaction/outlines/create_op_return_outline_test.go
  engine/transaction/outlines/create_outline_test.go
  engine/transaction/outlines/create_paymail_outline_test.go
  engine/transaction/outlines/evaluation_context.go
  engine/transaction/outlines/inteface.go
  engine/transaction/outlines/interface.go
  engine/transaction/outlines/internal/evaluation/context.go
  engine/transaction/outlines/internal/evaluation/interface.go
  engine/transaction/outlines/output_op_return.go
  engine/transaction/outlines/output_paymail.go
  engine/transaction/outlines/output_specifications.go
  engine/transaction/outlines/testabilities/ability_outline_transaction.go
  engine/transaction/outlines/testabilities/assert_draft_transaction.go
  engine/transaction/outlines/testabilities/assert_outline_input.go
  engine/transaction/outlines/testabilities/assert_outline_output.go
  engine/transaction/outlines/testabilities/assert_outline_transaction.go
  engine/transaction/outlines/testabilities/fixture_outline_transaction.go
  engine/transaction/outlines/testabilities/mock_paymail_address_service.go
  engine/transaction/outlines/transaction.go
  engine/transaction/outlines/transaction_outlines_service.go
  engine/transaction/outlines/transaction_spec.go
  engine/transaction/outlines/utxo/internal/sql/inputs_query_composer.go
  engine/transaction/outlines/utxo/internal/sql/selector.go
  engine/transaction/outlines/utxo/internal/sql/selector_example_test.go
  engine/transaction/outlines/utxo/internal/sql/selector_test.go
  engine/transaction/outlines/utxo/internal/sql/testabilities/assertions_inputs_selector.go
  engine/transaction/outlines/utxo/internal/sql/testabilities/fixture_inputs_selector.go
  engine/transaction/outlines/utxo/internal/sql/testabilities/testability_inputs_selector.go
  engine/v2/paymails/interface.go
  engine/v2/paymails/paymailerrors/paymail_errors.go
  engine/v2/paymails/paymails_service.go
Labels: tested, regression-tests

#871 Task(SPV-1428) change feature flag name from new transaction flow enabled to v2
  actions/paymailserver/incoming_paymail_tx_test.go
  actions/paymailserver/stateless_capabilities_test.go
  actions/v2/admin/users/create_test.go
  actions/v2/admin/users/paymail_add_test.go
  actions/v2/operations/search_test.go
  actions/v2/transactions/outlines_endpoint_test.go
  actions/v2/transactions/outlines_record_test.go
  actions/v2/transactions/routes.go
  actions/v2/users/current_test.go
  config/config.go
  config/config_to_options.go
  engine/testabilities/fixture_configopts.go
  engine/testabilities/fixture_engine.go
  engine/v2/transaction/outlines/utxo/internal/sql/testabilities/fixture_inputs_selector.go
  server/server.go
Labels: tested, regression-tests

#865 deps(SPV-1411): switch mapstructure to viper
  actions/v2/transactions/internal/mapping/outline/outline_request_to_engine.go
  actions/v2/transactions/internal/mapping/outline/outline_to_response.go
  config/load_config.go
  go.mod
  go.sum
  internal/query/parse.go
Labels: automerge, tested, regression-tests

#874 feat(SPV-1121): adjust op_return recording to domain services approach
  actions/testabilities/fixture_spvwallet_application.go
  actions/v2/transactions/internal/mapping/recorded_outline.go
  actions/v2/transactions/internal/mapping/transaction_outline.go
  actions/v2/transactions/outlines_record.go
  actions/v2/transactions/outlines_record_test.go
  actions/v2/transactions/routes.go
  engine/testabilities/faucet_fixture.go
  engine/testabilities/fixture_engine.go
  engine/tester/fixtures/tx_fixtures.go
  engine/tester/fixtures/users_fixtures.go
  engine/tester/jsonrequire/funcs.go
  engine/v2/addresses/addresses_service.go
  engine/v2/addresses/addressesmodels/address.go
  engine/v2/addresses/interface.go
  engine/v2/database/data.go
  engine/v2/database/repository/addresses.go
  engine/v2/database/repository/operations.go
  engine/v2/database/repository/outputs.go
  engine/v2/database/tracked_transaction.go
  engine/v2/database/user_utxos.go
  engine/v2/keys/type42/derivation.go
  engine/v2/keys/type42/destination.go
  engine/v2/keys/type42/destination_test.go
  engine/v2/paymailserver/paymail_service_provider.go
  engine/v2/transaction/record/interface.go
  engine/v2/transaction/record/op_return.go
  engine/v2/transaction/record/operation_wrapper.go
  engine/v2/transaction/record/record_outline.go
  engine/v2/transaction/record/record_paymail_transaction.go
  engine/v2/transaction/record/service.go
  engine/v2/transaction/record/tx_flow.go
  engine/v2/transaction/txmodels/new_operation.go
  engine/v2/transaction/txmodels/new_output.go
  engine/v2/transaction/txmodels/new_transaction.go
  engine/v2/transaction/txmodels/recorded_outline.go
  engine/v2/transaction/txmodels/tracked_output.go
  engine/v2/transaction/txmodels/tx_status.go
  models/request/annotated_transaction.go
  models/response/record_outline.go
Labels: tested, regression-tests

#878 feat(SPV-1398): change outline response to be prepared for BEEF and Raw formatting of transaction.
  actions/v2/transactions/internal/mapping/annotatedtx/annotated_tx_request_to_engine.go
  actions/v2/transactions/internal/mapping/outline/outline_to_response.go
  actions/v2/transactions/internal/mapping/transaction_outline.go
  actions/v2/transactions/outlines.go
  actions/v2/transactions/outlines_endpoint_test.go
  actions/v2/transactions/outlines_record_test.go
  engine/v2/bsv/transaction_hex.go
  engine/v2/transaction/outlines/create_op_return_outline_test.go
  engine/v2/transaction/outlines/create_outline_test.go
  engine/v2/transaction/outlines/create_paymail_outline_test.go
  engine/v2/transaction/outlines/interface.go
  engine/v2/transaction/outlines/testabilities/assert_outline_transaction.go
  engine/v2/transaction/outlines/transaction_outlines_service.go
  engine/v2/transaction/record/record_outline.go
  models/transaction/annotated_transaction.go
Labels: tested, regression-tests

#877 feat(SPV-1125) finalize the story for op_return recording
  .gitignore
  actions/v2/data/get.go
  actions/v2/data/get_test.go
  actions/v2/data/internal/mapping/data.go
  actions/v2/data/routes.go
  actions/v2/operations/search.go
  actions/v2/register.go
  actions/v2/transactions/outlines_record_test.go
  engine/client.go
  engine/client_internal.go
  engine/interface.go
  engine/spverrors/definitions.go
  engine/testabilities/fixture_engine.go
  engine/testabilities/fixture_faucet.go
  engine/v2/data/data_service.go
  engine/v2/data/datamodels/data.go
  engine/v2/data/interface.go
  engine/v2/database/repository/all.go
  engine/v2/database/repository/data.go
  models/bsv/outpoint.go
  models/response/data.go
  models/response/recorded_outline.go
Labels: tested
