Repository bitcoin-sv/spv-wallet, pull requests merged in 2025-02, with the labels that each got.

#881 feat: allow configuring arc status to wait for when broadcasting transactions
  config/config.go
  config/config_to_options.go
  engine/chain/internal/arc/broadcast.go
  engine/chain/models/arc_config.go
Labels: tested, regression-tests

#887 feat(SPV-1398): select inputs for outline
  actions/testabilities/assert_spvwallet_application.go
  actions/v2/transactions/internal/mapping/outline_tx.go
  actions/v2/transactions/internal/testabilities/ability_transactions_endpoint.go
  actions/v2/transactions/internal/testabilities/assert_transactions_endpoint.go
  actions/v2/transactions/internal/testabilities/fixture_transactions_endpoints.go
  actions/v2/transactions/outlines.go
  actions/v2/transactions/outlines_endpoint_test.go
  engine/client_internal.go
  engine/testabilities/fixture_faucet.go
  engine/tester/jsonrequire/funcs.go
  engine/tester/jsonrequire/getter.go
  engine/tester/jsonrequire/placeholders.go
  engine/tester/jsonrequire/xpath.go
  engine/v2/bsv/bsverrors/bsv_errors.go
  engine/v2/bsv/transaction_hex.go
  engine/v2/transaction/annotation.go
  engine/v2/transaction/outlines/create_op_return_outline_test.go
  engine/v2/transaction/outlines/create_outline_test.go
  engine/v2/transaction/outlines/create_paymail_outline_test.go
  engine/v2/transaction/outlines/evaluation_context.go
  engine/v2/transaction/outlines/inputs_specifications.go
  engine/v2/transaction/outlines/interface.go
  engine/v2/transaction/outlines/testabilities/assert_outline_input.go
  engine/v2/transaction/outlines/testabilities/assert_outline_transaction.go
  engine/v2/transaction/outlines/testabilities/fixture_outline_transaction.go
  engine/v2/transaction/outlines/testabilities/mocked_utxo_selector.go
  engine/v2/transaction/outlines/transaction_outlines_service.go
  engine/v2/transaction/outlines/transaction_spec.go
  engine/v2/transaction/outlines/utxo/internal/sql/inputs_query_composer.go
  engine/v2/transaction/outlines/utxo/internal/sql/selector.go
  engine/v2/transaction/outlines/utxo/internal/sql/selector_example_test.go
  engine/v2/transaction/outlines/utxo/internal/sql/selector_test.go
  engine/v2/transaction/outlines/utxo/internal/sql/testabilities/assertions_inputs_selector.go
  engine/v2/transaction/outlines/utxo/internal/sql/testabilities/fixture_inputs_selector.go
  engine/v2/transaction/outlines/utxo/internal/sql/testabilities/testability_inputs_selector.go
  engine/v2/transaction/outlines/utxo/selector.go
  models/request/opreturn/data_type.go
  models/transaction/annotated_transaction.go
Labels: tested

#888 fix(SPV-1494): fix failure when trying to send BEEF transaction with multiple inputs from single transaction.
  engine/beef_bump.go
  engine/beef_bump_debug_test.go
Labels: tested, regression-tests

#889 fix(SPV-1494): panic on start up
  engine/client.go
Labels: tested, regression-tests

#885 feat(SPV-1168): tests for record outline twice & double spend attempt
  actions/v2/transactions/outlines_record_doublespanding_test.go
  actions/v2/transactions/outlines_record_opreturn_test.go
Labels: test, tested, regression-tests

#882 feat(SPV-1429): paymailDomain validation on domain-services level & error mapping for http response
  actions/v2/admin/errors/errors.go
  actions/v2/admin/users/create.go
  actions/v2/admin/users/paymail_add.go
  cmd/main.go
  config/config.go
  config/errors/errors.go
  config/utils.go
  config/validate_paymail.go
  engine/client.go
  engine/client_internal.go
  engine/client_options.go
  engine/spverrors/map_error_response.go
  engine/testabilities/fixture_engine.go
  engine/v2/paymails/paymails_service.go
  engine/v2/users/users_service.go
  initializer/config_to_options.go
  tests/tests.go
Labels: tested, regression-tests

#880 feat(SPV-1157) use broadcast status returned from ARC
  actions/paymailserver/incoming_paymail_tx_test.go
  actions/v2/operations/internal/mapping/operations.go
  actions/v2/operations/search.go
  actions/v2/transactions/outlines_record_opreturn_test.go
  engine/client.go
  engine/client_internal.go
  engine/interface.go
  engine/v2/database/dbquery/paginate.go
  engine/v2/database/dbquery/scopes.go
  engine/v2/database/repository/operations.go
  engine/v2/operations/interface.go
  engine/v2/operations/operations_service.go
  engine/v2/operations/operationsmodels/operation.go
  engine/v2/transaction/record/tx_flow.go
  models/paged_result.go
  models/response/operation.go
Labels: tested, regression-tests

#892 feat(SPV-1471): create and implement admin status endpoint with openapi3
  .yamllint.yml
  actions/v2/admin/status.go
  actions/v2/admin/status_test.go
  actions/v2/server.go
  api/README.md
  api/common/template.yaml
  api/components/errors.yaml
  api/components/models.yaml
  api/components/requests.yaml
  api/components/responses.yaml
  api/endpoints/admin.yaml
  api/endpoints/base.yaml
  api/endpoints/user.yaml
  api/gen.api.go
  api/gen.api.yaml
  api/gen.models.go
  engine/spverrors/definitions.go
  go.mod
  go.sum
  server/middleware/scopes_middleware.go
  server/server.go
  server/server_test.go
  tools/apigen.go
  tools/cfg-models.yaml
  tools/merge_yamls.go
  tools/oapi-config.yaml
  tools/tools.go
Labels: tested

#858 feat(SPV-1391): add source transaction builder.
  engine/v2/transaction/beef/beef_service.go
  engine/v2/transaction/beef/beef_service_test.go
  engine/v2/transaction/beef/source_transaction_resolver.go
  engine/v2/transaction/beef/testabilities/assert_beef_tx.go
  engine/v2/transaction/beef/testabilities/tx_graph_builder.go
  engine/v2/transaction/beef/testabilities/tx_repository.go
  engine/v2/transaction/beef/testabilities/tx_scripts.go
  engine/v2/transaction/errors/errors.go
Labels: tested

#898 feat(SPV-1475): register v2 swagger
  actions/v2/base/routes.go
  actions/v2/register.go
Labels: tested

#897 feat(SPV-1471): add configs shared v2 endpoint
  actions/sharedconfig/get.go
  actions/v2/admin/server.go
  actions/v2/admin/status.go
  actions/v2/base/server.go
  actions/v2/base/shared_config.go
  actions/v2/base/shared_config_test.go
  actions/v2/server.go
  api/components/models.yaml
  api/components/responses.yaml
  api/endpoints/base.yaml
  api/gen.api.go
  api/gen.api.yaml
  api/gen.models.go
  server/server.go
Labels: tested, regression-tests

#904 fix(SPV-1350): (v1) update tx in db when sth changed
  engine/model_transactions.go
  engine/tx_sync_task.go
Labels: bug-P3, tested, regression-tests

#900 feat(SPV-1486) outgoing transactions with notify p2p
  actions/testabilities/ability_spvwallet_application.go
  actions/testabilities/assert_spvwallet_application.go
  actions/testabilities/assert_spvwallet_user.go
  actions/testabilities/fixture_spvwallet_application.go
  actions/v2/transactions/internal/testabilities/ability_transactions_endpoint.go
  actions/v2/transactions/internal/testabilities/assert_transactions_endpoint.go
  actions/v2/transactions/outlines_record_paymail_external_test.go
  actions/v2/transactions/outlines_record_paymail_internal_test.go
  actions/v2/users/current.go
  engine/client_internal.go
  engine/contact_service_test.go
  engine/model_draft_transactions_test.go
  engine/paymail/paymail_service_client.go
  engine/paymail/paymail_service_client_interface.go
  engine/paymail/testabilities/test_paymail_service_client.go
  engine/testabilities/assert_engine.go
  engine/testabilities/assert_paymail_external.go
  engine/testabilities/fixture_arc.go
  engine/testabilities/fixture_engine.go
  engine/testabilities/fixture_faucet.go
  engine/tester/fixtures/users_fixtures.go
  engine/tester/logger.go
  engine/tester/paymailmock/http_sniffer.go
  engine/tester/paymailmock/mock_capability.go
  engine/tester/paymailmock/mock_capability_factories.go
  engine/tester/paymailmock/mock_paymail_client.go
  engine/tester/paymailmock/mock_paymail_domain_name.go
  engine/tester/paymailmock/mock_paymail_host_responses.go
  engine/tester/paymailmock/mock_paymail_recordtx_response.go
  engine/v2/database/repository/operations.go
  engine/v2/database/repository/users.go
  engine/v2/transaction/errors/errors.go
  engine/v2/transaction/record/interface.go
  engine/v2/transaction/record/paymail.go
  engine/v2/transaction/record/record_outline.go
  engine/v2/transaction/record/record_paymail_transaction.go
  engine/v2/transaction/record/service.go
  engine/v2/users/interface.go
  engine/v2/users/users_service.go
Labels: feature, tested

#907 feat(SPV-000): bump go-paymail version
  go.mod
  go.sum
Labels: tested

#899 feat(SPV-1478): migrate existing admin v2 endpoints to openapi3
  actions/v2/admin/internal/mapping/paymail.go
  actions/v2/admin/internal/mapping/user.go
  actions/v2/admin/register.go
  actions/v2/admin/server.go
  actions/v2/admin/status.go
  actions/v2/admin/users/create.go
  actions/v2/admin/users/get.go
  actions/v2/admin/users/paymail_add.go
  actions/v2/admin/users/routes.go
  actions/v2/admin/users/server.go
  actions/v2/base/server.go
  actions/v2/base/shared_config.go
  actions/v2/base/shared_config_test.go
  actions/v2/register.go
  actions/v2/server.go
  actions/v2/swagger/swagger-ui.go
  api/components/errors.yaml
  api/components/models.yaml
  api/components/requests.yaml
  api/components/responses.yaml
  api/endpoints/admin.yaml
  api/endpoints/base.yaml
  api/gen.api.go
  api/gen.api.yaml
  api/gen.models.go
  models/request/adminrequest/paymail.go
  models/request/adminrequest/user.go
  server/server.go
  tools/merge_yamls.go
Labels: tested

#912 chore(bump): golang 1.24
  .golangci-lint.yml
  .golangci-style.yml
  Dockerfile
  go.mod
  models/go.mod
  regression_tests/go.mod
Labels: tested, regression-tests

#901 feat(SPV-1478): migrate existing endpoints
  actions/testabilities/assert_spvwallet_user.go
  actions/v2/api.go
  actions/v2/data/get.go
  actions/v2/data/internal/mapping/data.go
  actions/v2/data/routes.go
  actions/v2/data/server.go
  actions/v2/operations/internal/mapping/operations.go
  actions/v2/operations/routes.go
  actions/v2/operations/search.go
  actions/v2/operations/server.go
  actions/v2/register.go
  actions/v2/server.go
  actions/v2/transactions/internal/mapping/annotated_tx.go
  actions/v2/transactions/internal/mapping/outline_tx.go
  actions/v2/transactions/internal/mapping/recorded_outline.go
  actions/v2/transactions/outlines.go
  actions/v2/transactions/outlines_record.go
  actions/v2/transactions/routes.go
  actions/v2/transactions/server.go
  actions/v2/users/current.go
  actions/v2/users/routes.go
  actions/v2/users/server.go
  api/components/errors.yaml
  api/components/models.yaml
  api/components/requests.yaml
  api/components/responses.yaml
  api/endpoints/admin.yaml
  api/endpoints/base.yaml
  api/endpoints/user.yaml
  api/gen.api.go
  api/gen.api.yaml
  api/gen.models.go
  engine/v2/transaction/annotation.go
  engine/v2/transaction/outlines/create_op_return_outline_test.go
  engine/v2/transaction/outlines/output_op_return.go
  engine/v2/transaction/outlines/output_paymail.go
  lox/catch.go
  lox/mapper.go
  models/request/annotated_transaction.go
  models/response/adminresponse/paymail.go
  models/response/adminresponse/user.go
  models/response/operation.go
  models/response/recorded_outline.go
  models/response/user_info.go
  models/transaction/annotated_transaction.go
  server/middleware/scopes_middleware.go
  server/server.go
Labels: tested

#906 task(SPV-1473) Prevent tools.go pattern from compiling generators into production binary
  api/README.md
Labels: tested

#916 chore(SPV-1554): remove tests which requires actual redis connection
  .github/workflows/run-tests.yml
  engine/client_options_test.go
  engine/taskmanager/taskq_test.go
  engine/tester/cache_test.go
  engine/tester/tester_test.go
Labels: tested

#917 feat(SPV-1483): add unconfirm contact endpoint and related functionality
  actions/admin/contact.go
  actions/admin/routes.go
  engine/action_contact.go
  engine/interface.go
Labels: feature, tested, regression-tests

#910 feat(SPV-1059) fee and change
  .golangci-lint.yml
  actions/paymailserver/incoming_paymail_tx_test.go
  actions/testabilities/assert_spvwallet_application.go
  actions/testabilities/assert_transactions_endpoint.go
  actions/v2/transactions/internal/mapping/outline_tx.go
  actions/v2/transactions/internal/testabilities/ability_transactions_endpoint.go
  actions/v2/transactions/internal/testabilities/assert_transaction_details.go
  actions/v2/transactions/internal/testabilities/assert_transactions_endpoint.go
  actions/v2/transactions/internal/testabilities/fixture_transactions_endpoints.go
  actions/v2/transactions/outlines_endpoint_test.go
  actions/v2/transactions/outlines_suite_test.go
  api/components/models.yaml
  api/gen.api.yaml
  api/gen.models.go
  engine/client_internal.go
  engine/paymail/paymail_test.go
  engine/paymail/testabilities/assert_paymail_service_client.go
  engine/paymail/testabilities/fixture_paymail_service_client.go
  engine/testabilities/assert_engine.go
  engine/testabilities/assert_paymail_external.go
  engine/testabilities/fixture_faucet.go
  engine/tester/fixtures/tx_fixtures.go
  engine/tester/jsonrequire/funcs.go
  engine/tester/paymailmock/mock_capability.go
  engine/tester/paymailmock/mock_capability_factories.go
  engine/tester/paymailmock/mock_paymail_host_responses.go
  engine/v2/database/testabilities/fixture_database.go
  engine/v2/database/testabilities/user_utxo_fixture.go
  engine/v2/keys/type42/destination.go
  engine/v2/keys/type42/destination_test.go
  engine/v2/keys/type42/errors.go
  engine/v2/paymailserver/paymail_service_provider.go
  engine/v2/transaction/annotation.go
  engine/v2/transaction/beef/testabilities/assert_beef_tx.go
  engine/v2/transaction/errors/errors.go
  engine/v2/transaction/outlines/add_change.go
  engine/v2/transaction/outlines/create_outline_withchange_test.go
  engine/v2/transaction/outlines/create_paymail_outline_test.go
  engine/v2/transaction/outlines/evaluation_context.go
  engine/v2/transaction/outlines/inputs_specifications.go
  engine/v2/transaction/outlines/interface.go
  engine/v2/transaction/outlines/output_specifications.go
  engine/v2/transaction/outlines/testabilities/ability_outline_transaction.go
  engine/v2/transaction/outlines/testabilities/assert_outline_output.go
  engine/v2/transaction/outlines/testabilities/assert_outline_transaction.go
  engine/v2/transaction/outlines/testabilities/fixture_outline_transaction.go
  engine/v2/transaction/outlines/testabilities/mock_transaction_beef_service.go
  engine/v2/transaction/outlines/testabilities/mocked_utxo_selector.go
  engine/v2/transaction/outlines/transaction_outlines_service.go
  engine/v2/transaction/outlines/transaction_spec.go
  engine/v2/transaction/outlines/utxo/internal/sql/calculate_size.go
  engine/v2/transaction/outlines/utxo/internal/sql/inputs_query_composer.go
  engine/v2/transaction/outlines/utxo/internal/sql/selector.go
  engine/v2/transaction/outlines/utxo/internal/sql/selector_example_test.go
  engine/v2/transaction/outlines/utxo/internal/sql/selector_test.go
  engine/v2/transaction/outlines/utxo/internal/sql/testabilities/assertions_inputs_selector.go
Labels: tested

#921 fix(SPV-1465): fix invalid setting transaction input sources
  engine/v2/database/repository/operations.go
  engine/v2/database/tracked_transaction.go
  engine/v2/transaction/record/tx_flow.go
  engine/v2/transaction/txmodels/new_transaction.go
Labels: tested

#922 fix(SPV-1560): created transaction has wrong nSequence on inputs
  engine/v2/transaction/outlines/create_op_return_outline_test.go
  engine/v2/transaction/outlines/create_paymail_outline_test.go
  engine/v2/transaction/outlines/inputs_specifications.go
  engine/v2/transaction/outlines/testabilities/assert_outline_transaction.go
Labels: automerge, tested

#929 test(SPV-1549): proposition to use interfaces
  actions/v2/internal/integrationtests/spend_external_funds_internally_test.go
  actions/v2/internal/testabilities/ability_actions.go
  actions/v2/internal/testabilities/ability_integration_tests.go
  actions/v2/internal/testabilities/assert_actors.go
  actions/v2/internal/testabilities/fixture_user_actors.go
Labels: tested

#928 fix(SPV-1561): cannot make new transaction on postgres
  engine/v2/database/repository/operations.go
  engine/v2/database/tracked_output.go
Labels: automerge, tested

#932 feat(SPV-1474): Swagger v2 adjustments
  actions/v2/swagger/swagger-ui.go
  api/common/template.yaml
  api/embeded_openapi_yaml.go
  api/gen.api.yaml
  api/manualtests/client/client.gen.go
Labels: tested, regression-tests

#934 fix(SPV-1569) arc callback url
  engine/action_transaction.go
  initializer/config_to_options.go
Labels: tested

#926 feat(SPV-1555) record change output
  .golangci-lint.yml
  actions/testabilities/assert_spvwallet_user.go
  actions/v2/internal/integrationtests/spend_external_funds_internally_test.go
  actions/v2/transactions/internal/mapping/annotated_tx.go
  actions/v2/transactions/internal/mapping/outline_tx.go
  actions/v2/transactions/internal/testabilities/assert_transaction_details.go
  actions/v2/transactions/outlines_record_withchange_test.go
  engine/client_internal.go
  engine/tester/fixtures/tx_fixtures.go
  engine/tester/fixtures/unlocking_resolver.go
  engine/tester/fixtures/users_fixtures.go
  engine/v2/custominstructions/errors/errors.go
  engine/v2/custominstructions/interface.go
  engine/v2/custominstructions/interpreter.go
  engine/v2/custominstructions/interpreter_test.go
  engine/v2/custominstructions/locking_resolver.go
  engine/v2/custominstructions/types.go
  engine/v2/keys/type42/derivation.go
  engine/v2/keys/type42/destination.go
  engine/v2/keys/type42/pki.go
  engine/v2/transaction/annotation.go
  engine/v2/transaction/outlines/output_specifications.go
  engine/v2/transaction/outlines/testabilities/assert_outline_output.go
  engine/v2/transaction/outlines/testabilities/assert_outline_transaction.go
  engine/v2/transaction/record/addresses.go
  engine/v2/transaction/record/custom_outputs.go
  engine/v2/transaction/record/interface.go
  engine/v2/transaction/record/op_return.go
  engine/v2/transaction/record/paymail.go
  engine/v2/transaction/record/record_outline.go
  engine/v2/transaction/record/record_paymail_transaction.go
  engine/v2/transaction/record/service.go
  engine/v2/transaction/record/tx_flow.go
Labels: tested

#940 test(SPV-1549): refactor txfixture into testability.
  actions/paymailserver/incoming_paymail_tx_test.go
  actions/paymailserver/old_incoming_paymail_tx_test.go
  actions/testabilities/fixture_spvwallet_application.go
  actions/v2/data/get_test.go
  actions/v2/internal/integrationtests/testabilities/ability_actions.go
  actions/v2/internal/integrationtests/testabilities/fixture_user_actors.go
  actions/v2/transactions/internal/testabilities/assert_transaction_details.go
  actions/v2/transactions/outlines_record_doublespanding_test.go
  actions/v2/transactions/outlines_record_opreturn_test.go
  actions/v2/transactions/outlines_record_paymail_external_test.go
  actions/v2/transactions/outlines_record_paymail_internal_test.go
  actions/v2/transactions/outlines_record_withchange_test.go
  engine/chain/internal/ef/converter_test.go
  engine/testabilities/fixture_engine.go
  engine/testabilities/fixture_faucet.go
  engine/tester/fixtures/txtestability/ability_transaction.go
  engine/tester/fixtures/txtestability/fixture_tx.go
  engine/tester/fixtures/txtestability/fixture_tx_test.go
  engine/tester/fixtures/unlocking_resolver.go
  engine/v2/transaction/outlines/testabilities/assert_outline_output.go
  engine/v2/transaction/outlines/testabilities/assert_outline_transaction.go
  engine/v2/transaction/outlines/utxo/internal/sql/testabilities/fixture_inputs_selector.go
Labels: tested
